<script>
	import { onMount } from 'svelte'
	import Svelvet from 'svelvet'

	let pageHeight
	let pageWidth
	// onMount(() => {
	// 	pageHeight = document.window.innerHeight
	// 	pageWidth = document.window.innerWidth
	// })

	const initialNodes = [
		{
			id: 1,
			position: { x: 350, y: 210 },
			data: { label: 'الفرض العيني' },
			width: 125,
			height: 40,
			bgColor: 'white',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 2,
			position: { x: 250, y: 65 },
			data: { label: 'علم التوحيد' },
			width: 80,
			height: 40,
			bgColor: '#61FFA3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#61FFA3',
		},
		{
			id: 3,
			position: { x: 50, y: 35 },
			data: {
				label: 'معرفة العقائد الواجبة والمتسحيلة والجائزة في حق اللع تعالى ورسله عليهم الصلاة والسلام والإيمان بالسمعيات',
			},
			width: 175,
			height: 100,
			bgColor: '#61FFA3',
			borderColor: '#61FFA3',
			targetPosition: 'right',
		},
		{
			id: 4,
			position: { x: 250, y: 150 },
			data: { label: 'علم التجويد' },
			width: 80,
			height: 40,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 5,
			position: { x: 100, y: 150 },
			data: {
				label: 'إتقان تلاوة القرآن وترتيله',
			},
			width: 125,
			height: 40,
			bgColor: '#A2FDFF',
			borderColor: '#A2FDFF',
			targetPosition: 'right',
		},
		{
			id: 6,
			position: { x: 250, y: 210 },
			data: { label: 'علم العبادات' },
			width: 80,
			height: 40,
			bgColor: '#A7B7FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A7B7FF',
		},
		{
			id: 7,
			position: { x: 50, y: 205 },
			data: {
				label: 'الإتيان بالعبادات على الوجه الشرعي الصحيح',
			},
			width: 175,
			height: 50,
			bgColor: '#A7B7FF',
			borderColor: '#A7B7FF',
			targetPosition: 'right',
		},
		{
			id: 8,
			position: { x: 250, y: 285 },
			data: { label: 'علم المعاملات' },
			width: 80,
			height: 40,
			bgColor: '#FFC5A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 9,
			position: { x: 50, y: 270 },
			data: {
				label: 'إجراء المعاملات الشاملة للبيوع، وأحكام الأسرة على الوجه الذي شرعه الله تعالى',
			},
			width: 175,
			height: 70,
			bgColor: '#FFC5A7',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 10,
			position: { x: 250, y: 370 },
			data: { label: 'علم التصوف' },
			width: 80,
			height: 40,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 11,
			position: { x: 50, y: 355 },
			data: {
				label: 'إصلاح القلب وتهذيب النفس',
			},
			width: 175,
			height: 70,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		// END FARD, START QURAN
		{
			id: 12,
			position: { x: 350, y: 580 },
			data: { label: 'القرآن الكريم وعلومه' },
			width: 125,
			height: 40,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 13,
			position: { x: 250, y: 500 },
			data: { label: 'علم التجويد' },
			width: 80,
			height: 40,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 14,
			position: { x: 50, y: 485 },
			data: {
				label: 'إتقان تلاوة القرآن وترتيله من خلال تدريب عملي ودراسة نظرية',
			},
			width: 175,
			height: 70,
			bgColor: '#A2FDFF',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 15,
			position: { x: 250, y: 580 },
			data: { label: 'علم التفسير' },
			width: 80,
			height: 40,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 16,
			position: { x: 50, y: 565 },
			data: {
				label: 'شرح وتدبر بعض معاني كتاب الله العزيز بالنظر إلى الظاهر والباطن والحد والمطلع',
			},
			width: 175,
			height: 70,
			bgColor: '#97D9FF',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 17,
			position: { x: 250, y: 660 },
			data: { label: 'علوم القرآن' },
			width: 80,
			height: 40,
			bgColor: '#97BFFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		{
			id: 18,
			position: { x: 50, y: 645 },
			data: {
				label: 'إتمام المعرفة حول كتاب الله تعالى وأساليب العلماء في تفسيره',
			},
			width: 175,
			height: 70,
			bgColor: '#97BFFF',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		// HADITH
		{
			id: 19,
			position: { x: 350, y: 870 },
			data: { label: 'الحديث وعلومه' },
			width: 125,
			height: 40,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 20,
			position: { x: 250, y: 870 },
			data: { label: 'متون الحديث' },
			width: 80,
			height: 40,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 21,
			position: { x: 50, y: 855 },
			data: {
				label: 'التعمق رواية ودراية في كلام سيّد الكونين ﷺ',
			},
			width: 175,
			height: 70,
			bgColor: '#00DF65',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 22,
			position: { x: 250, y: 950 },
			data: { label: 'علوم الحديث' },
			width: 80,
			height: 40,
			bgColor: '#00DF89',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF89',
		},
		{
			id: 23,
			position: { x: 50, y: 935 },
			data: {
				label: 'نننننننننننننننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#00DF89',
			targetPosition: 'right',
			borderColor: '#00DF89',
		},
		//
		{
			id: 24,
			position: { x: 250, y: 790 },
			data: { label: 'السيرة والشمائل' },
			width: 80,
			height: 40,
			bgColor: '#00DF35',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF35',
		},
		{
			id: 25,
			position: { x: 50, y: 775 },
			data: {
				label: 'نننننننننننننننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#00DF35',
			targetPosition: 'right',
			borderColor: '#00DF35',
		},
		// AQIDA
		{
			id: 26,
			position: { x: 350, y: 1085 },
			data: { label: 'العقيدة' },
			width: 125,
			height: 40,
			bgColor: '#61FFA3',
			sourcePosition: 'left',
			borderColor: '#61FFA3',
		},
		{
			id: 27,
			position: { x: 50, y: 1070 },
			data: {
				label: 'ننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#61FFA3',
			targetPosition: 'right',
			borderColor: '#61FFA3',
		},
		// FIQH
		{
			id: 28,
			position: { x: 350, y: 1360 },
			data: { label: 'الفقه وأصوله' },
			width: 125,
			height: 40,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 29,
			position: { x: 250, y: 1230 },
			data: { label: 'الفروع' },
			width: 80,
			height: 40,
			bgColor: '#FFE8A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 30,
			position: { x: 50, y: 1215 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFE8A7',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 31,
			position: { x: 250, y: 1315 },
			data: { label: 'الأصول' },
			width: 80,
			height: 40,
			bgColor: '#FFDEA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 32,
			position: { x: 50, y: 1300 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFDEA7',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 33,
			position: { x: 250, y: 1400 },
			data: { label: 'القواعد' },
			width: 80,
			height: 40,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 34,
			position: { x: 50, y: 1385 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFD3A7',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 35,
			position: { x: 250, y: 1485 },
			data: { label: 'الأدلة' },
			width: 80,
			height: 40,
			bgColor: '#FFCAA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		{
			id: 36,
			position: { x: 50, y: 1470 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFCAA7',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		// TASAWWUF
		{
			id: 37,
			position: { x: 350, y: 1675 },
			data: { label: 'التصوف' },
			width: 125,
			height: 40,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 38,
			position: { x: 250, y: 1635 },
			data: { label: 'السلوك' },
			width: 80,
			height: 40,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 39,
			position: { x: 50, y: 1620 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 40,
			position: { x: 250, y: 1725 },
			data: { label: 'العرفان' },
			width: 80,
			height: 40,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		{
			id: 41,
			position: { x: 50, y: 1710 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#DDFFB2',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		// ARABIYAH
		{
			id: 42,
			position: { x: 350, y: 2000 },
			data: { label: 'اللغة العربية' },
			width: 125,
			height: 40,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 43,
			position: { x: 250, y: 1865 },
			data: { label: 'النحو' },
			width: 80,
			height: 40,
			bgColor: '#ECB2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 44,
			position: { x: 50, y: 1850 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#ECB2FF',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 45,
			position: { x: 250, y: 1950 },
			data: { label: 'الصرف' },
			width: 80,
			height: 40,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 46,
			position: { x: 50, y: 1935 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#E2B2FF',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 47,
			position: { x: 250, y: 2040 },
			data: { label: 'البلاغة' },
			width: 80,
			height: 40,
			bgColor: '#D5B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 48,
			position: { x: 50, y: 2025 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#D5B2FF',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 49,
			position: { x: 250, y: 2125 },
			data: { label: 'للناطقين بغيرها' },
			width: 80,
			height: 40,
			bgColor: '#C6B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		{
			id: 50,
			position: { x: 50, y: 2110 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#C6B2FF',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		// VARIOUS
		{
			id: 51,
			position: { x: 350, y: 2400 },
			data: { label: 'البرامج المختلفة' },
			width: 125,
			height: 40,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 52,
			position: { x: 250, y: 2265 },
			data: { label: 'الدعوة والخطابة' },
			width: 80,
			height: 40,
			bgColor: '#FFB2E6',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 53,
			position: { x: 50, y: 2250 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2E6',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 54,
			position: { x: 250, y: 2355 },
			data: { label: 'دورة النساء' },
			width: 80,
			height: 40,
			bgColor: '#FFB2DA',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 55,
			position: { x: 50, y: 2340 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2DA',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 56,
			position: { x: 250, y: 2445 },
			data: { label: 'دورة الصغار' },
			width: 80,
			height: 40,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 57,
			position: { x: 50, y: 2430 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2CE',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 58,
			position: { x: 250, y: 2535 },
			data: { label: 'المنطق' },
			width: 80,
			height: 40,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 59,
			position: { x: 50, y: 2520 },
			data: {
				label: 'نننننننننننننن',
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
	]

	const initialEdges = [
		{
			id: 'e1-2',
			source: 1,
			target: 2,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e2-3',
			source: 2,
			target: 3,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-4',
			source: 1,
			target: 4,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e4-5',
			source: 4,
			target: 5,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-6',
			source: 1,
			target: 6,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e6-7',
			source: 6,
			target: 7,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-8',
			source: 1,
			target: 8,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e8-9',
			source: 8,
			target: 9,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-10',
			source: 1,
			target: 10,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e10-11',
			source: 10,
			target: 11,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// END FARD, START QURAN
		{
			id: 'e12-13',
			source: 12,
			target: 13,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-15',
			source: 12,
			target: 15,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-17',
			source: 12,
			target: 17,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e13-14',
			source: 13,
			target: 14,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e15-16',
			source: 15,
			target: 16,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e17-18',
			source: 17,
			target: 18,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// HADITH
		{
			id: 'e19-20',
			source: 19,
			target: 20,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-22',
			source: 19,
			target: 22,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-24',
			source: 19,
			target: 24,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e20-21',
			source: 20,
			target: 21,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e22-23',
			source: 22,
			target: 23,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e24-25',
			source: 24,
			target: 25,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		//
		{
			id: 'e26-27',
			source: 26,
			target: 27,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// FIQH
		{
			id: 'e28-29',
			source: 28,
			target: 29,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-31',
			source: 28,
			target: 31,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-33',
			source: 28,
			target: 33,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-35',
			source: 28,
			target: 35,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e29-30',
			source: 29,
			target: 30,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e31-32',
			source: 31,
			target: 32,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e33-34',
			source: 33,
			target: 34,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e35-36',
			source: 35,
			target: 36,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// TASAWWUF
		{
			id: 'e37-38',
			source: 37,
			target: 38,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e37-40',
			source: 37,
			target: 40,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e38-39',
			source: 38,
			target: 39,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e40-41',
			source: 40,
			target: 41,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// ARABIYAH
		{
			id: 'e42-43',
			source: 42,
			target: 43,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-45',
			source: 42,
			target: 45,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-47',
			source: 42,
			target: 47,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-49',
			source: 42,
			target: 49,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e43-44',
			source: 43,
			target: 44,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e45-46',
			source: 45,
			target: 46,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e47-48',
			source: 47,
			target: 48,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e49-50',
			source: 49,
			target: 50,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// VARIOUS
		{
			id: 'e51-52',
			source: 51,
			target: 52,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-54',
			source: 51,
			target: 54,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-56',
			source: 51,
			target: 56,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-58',
			source: 51,
			target: 58,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e52-53',
			source: 52,
			target: 53,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e54-55',
			source: 54,
			target: 55,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e56-57',
			source: 56,
			target: 57,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e58-59',
			source: 58,
			target: 59,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
	]
</script>

<h1>علوم الشريعة والحقيقة</h1>
<div>
	<Svelvet width={500} height={2650} nodes={initialNodes} edges={initialEdges} movement={true} />
</div>

<style>
	div {
		width: 500px;
		margin: 0 auto;
		border: 2px solid rgb(182, 255, 142);
		border-radius: 12px;
	}
	h1 {
		text-align: center;
	}
</style>
