<script>
	import { onMount } from 'svelte'
	import LL from '$i18n/i18n-svelte'
	import Svelvet from 'svelvet'

	let pageHeight //dont need it for breakpoints
	let pageWidth
	onMount(() => {
		// TODO: this is not dynamic... but onChange would detect viewport??
		pageHeight = window.innerHeight
		pageWidth = window.innerWidth
	})

	// these are all reactive so language changes without refresh update the chart
	$: initialNodesTiny = [
		{
			id: 1,
			position: { x: 249, y: 210 },
			data: { label: $LL.fields.fard.title() },
			width: 70,
			height: 45,
			bgColor: '#61FFA3',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 2,
			position: { x: 155, y: 60 },
			data: { label: $LL.fields.fard.tawhid_title() },
			width: 75,
			height: 40,
			bgColor: '#EBBAB9',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EBBAB9',
		},
		{
			id: 3.1,
			position: { x: 1, y: 25 },
			data: {
				label: $LL.fields.fard.tawhid_content1(),
			},

			width: 135,
			height: 30,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 3.2,
			position: { x: 1, y: 65 },
			data: {
				label: $LL.fields.fard.tawhid_content2(),
			},
			width: 135,
			height: 30,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 3.3,
			position: { x: 1, y: 105 },
			data: {
				label: $LL.fields.fard.tawhid_content3(),
			},
			width: 135,
			height: 30,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 4,
			position: { x: 155, y: 145 },
			data: { label: $LL.fields.fard.tajwid_title() },
			width: 75,
			height: 40,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 5,
			position: { x: 1, y: 145 },
			data: {
				label: $LL.fields.fard.tajwid_content(),
			},
			width: 135,
			height: 40,
			bgColor: '#A2FDFF',
			borderColor: '#A2FDFF',
			targetPosition: 'right',
		},
		{
			id: 6,
			position: { x: 155, y: 212 },
			data: { label: $LL.fields.fard.ibadat_title() },
			width: 75,
			height: 40,
			bgColor: '#A7B7FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A7B7FF',
		},
		{
			id: 7,
			position: { x: 1, y: 197 },
			data: {
				label: $LL.fields.fard.ibadat_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#A7B7FF',
			borderColor: '#A7B7FF',
			targetPosition: 'right',
		},
		{
			id: 8,
			position: { x: 155, y: 290 },
			data: { label: $LL.fields.fard.muamalat_title() },
			width: 75,
			height: 40,
			bgColor: '#FFC5A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 9.1,
			position: { x: 1, y: 275 },
			data: {
				label: $LL.fields.fard.muamalat_content1(),
			},
			width: 135,
			height: 40,
			bgColor: '#FFC5A7',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 9.2,
			position: { x: 1, y: 320 },
			data: {
				label: $LL.fields.fard.muamalat_content2(),
			},
			width: 135,
			height: 40,
			bgColor: '#FFC5A7',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 10,
			position: { x: 155, y: 370 },
			data: { label: $LL.fields.fard.tasawwuf_title() },
			width: 75,
			height: 40,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 11,
			position: { x: 1, y: 365 },
			data: {
				label: $LL.fields.fard.tasawwuf_content(),
			},
			width: 135,
			height: 40,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		// END FARD, START QURAN
		{
			id: 12,
			position: { x: 249, y: 565 },
			data: { label: $LL.fields.quran.title() },
			width: 70,
			height: 70,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 13,
			position: { x: 155, y: 500 },
			data: { label: $LL.fields.fard.tajwid_title() },
			width: 75,
			height: 40,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 14,
			position: { x: 1, y: 485 },
			data: {
				label: $LL.fields.quran.tajwid_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#A2FDFF',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 15,
			position: { x: 155, y: 580 },
			data: { label: $LL.fields.quran.tafsir_title() },
			width: 75,
			height: 40,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 16,
			position: { x: 1, y: 565 },
			data: {
				label: $LL.fields.quran.tafsir_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#97D9FF',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 17,
			position: { x: 155, y: 662 },
			data: { label: $LL.fields.quran.ulum_title() },
			width: 75,
			height: 40,
			bgColor: '#97BFFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		{
			id: 18,
			position: { x: 1, y: 645 },
			data: {
				label: $LL.fields.quran.ulum_content(),
			},
			width: 135,
			height: 75,
			bgColor: '#97BFFF',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		// HADITH
		{
			id: 19,
			position: { x: 249, y: 870 },
			data: { label: $LL.fields.hadith.title() },
			width: 70,
			height: 55,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 20,
			position: { x: 155, y: 867 },
			data: { label: $LL.fields.hadith.ulum_title() },
			width: 75,
			height: 45,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 21,
			position: { x: 1, y: 855 },
			data: {
				label: $LL.fields.hadith.ulum_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#00DF65',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 22,
			position: { x: 155, y: 788 },
			data: { label: $LL.fields.hadith.main_title() },
			width: 75,
			height: 45,
			sourcePosition: 'left',
			targetPosition: 'right',
			bgColor: '#00DF35',
			borderColor: '#00DF35',
		},
		{
			id: 23,
			position: { x: 1, y: 775 },

			data: {
				label: $LL.fields.hadith.main_content(),
			},
			width: 135,
			height: 70,
			targetPosition: 'right',
			bgColor: '#00DF35',
			borderColor: '#00DF35',
		},
		//
		{
			id: 24,
			position: { x: 155, y: 950 },
			data: { label: $LL.fields.hadith.seerah_title() },
			width: 75,
			height: 45,
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF89',
			bgColor: '#00DF89',
		},
		{
			id: 25,
			position: { x: 1, y: 935 },
			data: {
				label: $LL.fields.hadith.seerah_content(),
			},
			width: 135,
			height: 70,
			borderColor: '#00DF89',
			bgColor: '#00DF89',
			targetPosition: 'right',
		},
		// AQIDA
		{
			id: 26,
			position: { x: 249, y: 1085 },
			data: { label: $LL.fields.aqidah.title() },
			width: 70,
			height: 55,
			bgColor: '#D7D5A2',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 27,
			position: { x: 1, y: 1070 },
			data: {
				label: $LL.fields.aqidah.explanation(),
			},
			width: 135,
			height: 85,
			bgColor: '#D7D5A2',
			targetPosition: 'right',
			borderColor: '#D7D5A2',
		},
		// FIQH
		{
			id: 28,
			position: { x: 249, y: 1360 },
			data: { label: $LL.fields.fiqh.title() },
			width: 70,
			height: 55,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 29,
			position: { x: 155, y: 1230 },
			data: { label: $LL.fields.fiqh.furu_title() },
			width: 75,
			height: 55,
			bgColor: '#FFE8A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 30,
			position: { x: 1, y: 1215 },
			data: {
				label: $LL.fields.fiqh.furu_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFE8A7',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 31,
			position: { x: 155, y: 1315 },
			data: { label: $LL.fields.fiqh.usul_title() },
			width: 75,
			height: 55,
			bgColor: '#FFDEA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 32,
			position: { x: 1, y: 1300 },
			data: {
				label: $LL.fields.fiqh.usul_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFDEA7',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 33,
			position: { x: 155, y: 1400 },
			data: { label: $LL.fields.fiqh.qawaid_title() },
			width: 75,
			height: 55,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 34,
			position: { x: 1, y: 1385 },
			data: {
				label: $LL.fields.fiqh.qawaid_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFD3A7',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 35,
			position: { x: 155, y: 1485 },
			data: { label: $LL.fields.fiqh.adillah_title() },
			width: 75,
			height: 55,
			bgColor: '#FFCAA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		{
			id: 36,
			position: { x: 1, y: 1470 },
			data: {
				label: $LL.fields.fiqh.adillah_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFCAA7',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		// TASAWWUF
		{
			id: 37,
			position: { x: 249, y: 1675 },
			data: { label: $LL.fields.tasawwuf.title() },
			width: 70,
			height: 55,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 38,
			position: { x: 155, y: 1635 },
			data: { label: $LL.fields.tasawwuf.suluk_title() },
			width: 75,
			height: 55,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 39,
			position: { x: 1, y: 1605 },
			data: {
				label: $LL.fields.tasawwuf.suluk_content(),
			},
			width: 135,
			height: 100,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 40,
			position: { x: 155, y: 1725 },
			data: { label: $LL.fields.tasawwuf.irfan_title() },
			width: 75,
			height: 55,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		{
			id: 41,
			position: { x: 1, y: 1725 },
			data: {
				label: $LL.fields.tasawwuf.irfan_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#DDFFB2',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		// ARABIYAH
		{
			id: 42,
			position: { x: 249, y: 2000 },
			data: { label: $LL.fields.arabayyiah.title() },
			width: 70,
			height: 55,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 43,
			position: { x: 155, y: 1865 },
			data: { label: $LL.fields.arabayyiah.nahw_title() },
			width: 75,
			height: 55,
			bgColor: '#ECB2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 44,
			position: { x: 1, y: 1850 },
			data: {
				label: $LL.fields.arabayyiah.nahw_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#ECB2FF',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 45,
			position: { x: 155, y: 1950 },
			data: { label: $LL.fields.arabayyiah.sarf_title() },
			width: 75,
			height: 55,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 46,
			position: { x: 1, y: 1935 },
			data: {
				label: $LL.fields.arabayyiah.sarf_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#E2B2FF',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 47,
			position: { x: 155, y: 2040 },
			data: { label: $LL.fields.arabayyiah.balaghah_title() },
			width: 75,
			height: 55,
			bgColor: '#D5B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 48,
			position: { x: 1, y: 2025 },
			data: {
				label: $LL.fields.arabayyiah.balaghah_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#D5B2FF',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 49,
			position: { x: 155, y: 2110 },
			data: { label: $LL.fields.arabayyiah.natiq_title() },
			width: 75,
			height: 70,
			bgColor: '#C6B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		{
			id: 50,
			position: { x: 1, y: 2110 },
			data: {
				label: $LL.fields.arabayyiah.natiq_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#C6B2FF',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		// VARIOUS
		{
			id: 51,
			position: { x: 249, y: 2490 },
			data: { label: $LL.fields.baramij.title() },
			width: 70,
			height: 55,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 52,
			position: { x: 155, y: 2265 },
			data: { label: $LL.fields.baramij.dawah_title() },
			width: 75,
			height: 55,
			bgColor: '#FFB2E6',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 53,
			position: { x: 1, y: 2250 },
			data: {
				label: $LL.fields.baramij.dawah_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFB2E6',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 54,
			position: { x: 155, y: 2345 },
			data: { label: $LL.fields.baramij.nisa_title() },
			width: 75,
			height: 60,
			bgColor: '#FFB2DA',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 55,
			position: { x: 1, y: 2340 },
			data: {
				label: $LL.fields.baramij.nisa_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFB2DA',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 56,
			position: { x: 155, y: 2435 },
			data: { label: $LL.fields.baramij.atfal_title() },
			width: 75,
			height: 60,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 57,
			position: { x: 1, y: 2430 },
			data: {
				label: $LL.fields.baramij.atfal_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFB2CE',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 58,
			position: { x: 155, y: 2520 },
			data: { label: $LL.fields.baramij.zawjiyyah_title() },
			width: 75,
			height: 70,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 59,
			position: { x: 1, y: 2520 },
			data: {
				label: $LL.fields.baramij.zawjiyyah_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 60,
			position: { x: 155, y: 2615 },
			data: { label: $LL.fields.baramij.tarbiyah_title() },
			width: 75,
			height: 60,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 61,
			position: { x: 1, y: 2610 },
			data: {
				label: $LL.fields.baramij.tarbiyah_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 62,
			position: { x: 155, y: 2705 },
			data: { label: $LL.fields.baramij.aswat_title() },
			width: 75,
			height: 60,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 63,
			position: { x: 1, y: 2700 },
			data: {
				label: $LL.fields.baramij.aswat_content(),
			},
			width: 135,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
	]

	$: initialEdgesTiny = [
		{
			id: 'e1-2',
			source: 1,
			target: 2,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.1',
			source: 2,
			target: 3.1,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.2',
			source: 2,
			target: 3.2,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.3',
			source: 2,
			target: 3.3,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e1-4',
			source: 1,
			target: 4,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e4-5',
			source: 4,
			target: 5,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e1-6',
			source: 1,
			target: 6,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e6-7',
			source: 6,
			target: 7,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e1-8',
			source: 1,
			target: 8,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e8-9.1',
			source: 8,
			target: 9.1,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e8-9.2',
			source: 8,
			target: 9.2,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e1-10',
			source: 1,
			target: 10,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e10-11',
			source: 10,
			target: 11,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		// END FARD, START QURAN
		{
			id: 'e12-13',
			source: 12,
			target: 13,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-15',
			source: 12,
			target: 15,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-17',
			source: 12,
			target: 17,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e13-14',
			source: 13,
			target: 14,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e15-16',
			source: 15,
			target: 16,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e17-18',
			source: 17,
			target: 18,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		// HADITH
		{
			id: 'e19-20',
			source: 19,
			target: 20,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-22',
			source: 19,
			target: 22,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-24',
			source: 19,
			target: 24,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e20-21',
			source: 20,
			target: 21,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e22-23',
			source: 22,
			target: 23,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e24-25',
			source: 24,
			target: 25,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e26-27',
			source: 26,
			target: 27,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		// FIQH
		{
			id: 'e28-29',
			source: 28,
			target: 29,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-31',
			source: 28,
			target: 31,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-33',
			source: 28,
			target: 33,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-35',
			source: 28,
			target: 35,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e29-30',
			source: 29,
			target: 30,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e31-32',
			source: 31,
			target: 32,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e33-34',
			source: 33,
			target: 34,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e35-36',
			source: 35,
			target: 36,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		// TASAWWUF
		{
			id: 'e37-38',
			source: 37,
			target: 38,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e37-40',
			source: 37,
			target: 40,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e38-39',
			source: 38,
			target: 39,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e40-41',
			source: 40,
			target: 41,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		// ARABIYAH
		{
			id: 'e42-43',
			source: 42,
			target: 43,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-45',
			source: 42,
			target: 45,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-47',
			source: 42,
			target: 47,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-49',
			source: 42,
			target: 49,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e43-44',
			source: 43,
			target: 44,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e45-46',
			source: 45,
			target: 46,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e47-48',
			source: 47,
			target: 48,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e49-50',
			source: 49,
			target: 50,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		// VARIOUS
		{
			id: 'e51-52',
			source: 51,
			target: 52,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-54',
			source: 51,
			target: 54,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-56',
			source: 51,
			target: 56,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-58',
			source: 51,
			target: 58,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-60',
			source: 51,
			target: 60,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-62',
			source: 51,
			target: 62,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e52-53',
			source: 52,
			target: 53,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e54-55',
			source: 54,
			target: 55,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e56-57',
			source: 56,
			target: 57,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e58-59',
			source: 58,
			target: 59,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e60-61',
			source: 60,
			target: 61,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e62-63',
			source: 62,
			target: 63,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
	]

	$: initialNodesMobile = [
		{
			id: 1,
			position: { x: 300, y: 230 },
			data: { label: $LL.fields.fard.title() },
			width: 125,
			height: 55,
			bgColor: '#61FFA3',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 2,
			position: { x: 200, y: 60 },
			data: { label: $LL.fields.fard.tawhid_title() },
			width: 80,
			height: 55,
			bgColor: '#EBBAB9',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EBBAB9',
		},
		{
			id: 3.1,
			position: { x: 1, y: 5 },
			data: {
				label: $LL.fields.fard.tawhid_content1(),
			},

			width: 175,
			height: 45,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 3.2,
			position: { x: 1, y: 55 },
			data: {
				label: $LL.fields.fard.tawhid_content2(),
			},
			width: 175,
			height: 45,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 3.3,
			position: { x: 1, y: 105 },
			data: {
				label: $LL.fields.fard.tawhid_content3(),
			},
			width: 175,
			height: 45,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 4,
			position: { x: 200, y: 165 },
			data: { label: $LL.fields.fard.tajwid_title() },
			width: 80,
			height: 55,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 5,
			position: { x: 1, y: 165 },
			data: {
				label: $LL.fields.fard.tajwid_content(),
			},
			width: 175,
			height: 45,
			bgColor: '#A2FDFF',
			borderColor: '#A2FDFF',
			targetPosition: 'right',
		},
		{
			id: 6,
			position: { x: 200, y: 230 },
			data: { label: $LL.fields.fard.ibadat_title() },
			width: 80,
			height: 55,
			bgColor: '#A7B7FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A7B7FF',
		},
		{
			id: 7,
			position: { x: 1, y: 225 },
			data: {
				label: $LL.fields.fard.ibadat_content(),
			},
			width: 175,
			height: 65,
			bgColor: '#A7B7FF',
			borderColor: '#A7B7FF',
			targetPosition: 'right',
		},
		{
			id: 8,
			position: { x: 200, y: 320 },
			data: { label: $LL.fields.fard.muamalat_title() },
			width: 80,
			height: 55,
			bgColor: '#FFC5A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 9.1,
			position: { x: 1, y: 300 },
			data: {
				label: $LL.fields.fard.muamalat_content1(),
			},
			width: 175,
			height: 45,
			bgColor: '#FFC5A7',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 9.2,
			position: { x: 1, y: 350 },
			data: {
				label: $LL.fields.fard.muamalat_content2(),
			},
			width: 175,
			height: 45,
			bgColor: '#FFC5A7',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 10,
			position: { x: 200, y: 400 },
			data: { label: $LL.fields.fard.tasawwuf_title() },
			width: 80,
			height: 55,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 11,
			position: { x: 1, y: 400 },
			data: {
				label: $LL.fields.fard.tasawwuf_content(),
			},
			width: 175,
			height: 55,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		// END FARD, START QURAN
		{
			id: 12,
			position: { x: 300, y: 580 },
			data: { label: $LL.fields.quran.title() },
			width: 125,
			height: 55,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 13,
			position: { x: 200, y: 500 },
			data: { label: $LL.fields.fard.tajwid_title() },
			width: 80,
			height: 55,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 14,
			position: { x: 1, y: 485 },
			data: {
				label: $LL.fields.quran.tajwid_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#A2FDFF',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 15,
			position: { x: 200, y: 580 },
			data: { label: $LL.fields.quran.tafsir_title() },
			width: 80,
			height: 55,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 16,
			position: { x: 1, y: 565 },
			data: {
				label: $LL.fields.quran.tafsir_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#97D9FF',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 17,
			position: { x: 200, y: 660 },
			data: { label: $LL.fields.quran.ulum_title() },
			width: 80,
			height: 55,
			bgColor: '#97BFFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		{
			id: 18,
			position: { x: 1, y: 645 },
			data: {
				label: $LL.fields.quran.ulum_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#97BFFF',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		// HADITH
		{
			id: 19,
			position: { x: 300, y: 870 },
			data: { label: $LL.fields.hadith.title() },
			width: 125,
			height: 55,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 20,
			position: { x: 200, y: 867 },
			data: { label: $LL.fields.hadith.ulum_title() },

			width: 80,
			height: 45,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 21,
			position: { x: 1, y: 855 },
			data: {
				label: $LL.fields.hadith.ulum_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#00DF65',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 22,
			position: { x: 200, y: 787 },
			data: { label: $LL.fields.hadith.main_title() },
			width: 80,
			height: 45,
			sourcePosition: 'left',
			targetPosition: 'right',
			bgColor: '#00DF35',
			borderColor: '#00DF35',
		},
		{
			id: 23,
			position: { x: 1, y: 775 },

			data: {
				label: $LL.fields.hadith.main_content(),
			},
			width: 175,
			height: 70,
			targetPosition: 'right',
			bgColor: '#00DF35',
			borderColor: '#00DF35',
		},
		//
		{
			id: 24,
			position: { x: 200, y: 950 },
			data: { label: $LL.fields.hadith.seerah_title() },
			width: 80,
			height: 45,

			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF89',
			bgColor: '#00DF89',
		},
		{
			id: 25,
			position: { x: 1, y: 935 },
			data: {
				label: $LL.fields.hadith.seerah_content(),
			},
			width: 175,
			height: 70,
			borderColor: '#00DF89',
			bgColor: '#00DF89',
			targetPosition: 'right',
		},
		// AQIDA
		{
			id: 26,
			position: { x: 300, y: 1085 },
			data: { label: $LL.fields.aqidah.title() },
			width: 125,
			height: 55,
			bgColor: '#D7D5A2',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 27,
			position: { x: 1, y: 1070 },
			data: {
				label: $LL.fields.aqidah.explanation(),
			},
			width: 175,
			height: 85,
			bgColor: '#D7D5A2',
			targetPosition: 'right',
			borderColor: '#D7D5A2',
		},
		// FIQH
		{
			id: 28,
			position: { x: 300, y: 1360 },
			data: { label: $LL.fields.fiqh.title() },
			width: 125,
			height: 55,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 29,
			position: { x: 200, y: 1230 },
			data: { label: $LL.fields.fiqh.furu_title() },
			width: 80,
			height: 55,
			bgColor: '#FFE8A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 30,
			position: { x: 1, y: 1215 },
			data: {
				label: $LL.fields.fiqh.furu_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFE8A7',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 31,
			position: { x: 200, y: 1315 },
			data: { label: $LL.fields.fiqh.usul_title() },
			width: 80,
			height: 55,
			bgColor: '#FFDEA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 32,
			position: { x: 1, y: 1300 },
			data: {
				label: $LL.fields.fiqh.usul_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFDEA7',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 33,
			position: { x: 200, y: 1400 },
			data: { label: $LL.fields.fiqh.qawaid_title() },
			width: 80,
			height: 55,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 34,
			position: { x: 1, y: 1385 },
			data: {
				label: $LL.fields.fiqh.qawaid_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFD3A7',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 35,
			position: { x: 200, y: 1485 },
			data: { label: $LL.fields.fiqh.adillah_title() },
			width: 80,
			height: 55,
			bgColor: '#FFCAA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		{
			id: 36,
			position: { x: 1, y: 1470 },
			data: {
				label: $LL.fields.fiqh.adillah_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFCAA7',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		// TASAWWUF
		{
			id: 37,
			position: { x: 300, y: 1675 },
			data: { label: $LL.fields.tasawwuf.title() },
			width: 125,
			height: 55,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 38,
			position: { x: 200, y: 1635 },
			data: { label: $LL.fields.tasawwuf.suluk_title() },
			width: 80,
			height: 55,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 39,
			position: { x: 1, y: 1615 },
			data: {
				label: $LL.fields.tasawwuf.suluk_content(),
			},
			width: 175,
			height: 80,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 40,
			position: { x: 200, y: 1725 },
			data: { label: $LL.fields.tasawwuf.irfan_title() },
			width: 80,
			height: 55,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		{
			id: 41,
			position: { x: 1, y: 1710 },
			data: {
				label: $LL.fields.tasawwuf.irfan_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#DDFFB2',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		// ARABIYAH
		{
			id: 42,
			position: { x: 300, y: 2000 },
			data: { label: $LL.fields.arabayyiah.title() },
			width: 125,
			height: 55,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 43,
			position: { x: 200, y: 1865 },
			data: { label: $LL.fields.arabayyiah.nahw_title() },
			width: 80,
			height: 55,
			bgColor: '#ECB2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 44,
			position: { x: 1, y: 1850 },
			data: {
				label: $LL.fields.arabayyiah.nahw_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#ECB2FF',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 45,
			position: { x: 200, y: 1950 },
			data: { label: $LL.fields.arabayyiah.sarf_title() },
			width: 80,
			height: 55,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 46,
			position: { x: 1, y: 1935 },
			data: {
				label: $LL.fields.arabayyiah.sarf_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#E2B2FF',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 47,
			position: { x: 200, y: 2040 },
			data: { label: $LL.fields.arabayyiah.balaghah_title() },
			width: 80,
			height: 55,
			bgColor: '#D5B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 48,
			position: { x: 1, y: 2025 },
			data: {
				label: $LL.fields.arabayyiah.balaghah_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#D5B2FF',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 49,
			position: { x: 200, y: 2110 },
			data: { label: $LL.fields.arabayyiah.natiq_title() },
			width: 85,
			height: 70,
			bgColor: '#C6B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		{
			id: 50,
			position: { x: 1, y: 2110 },
			data: {
				label: $LL.fields.arabayyiah.natiq_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#C6B2FF',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		// VARIOUS
		{
			id: 51,
			position: { x: 300, y: 2490 },
			data: { label: $LL.fields.baramij.title() },
			width: 125,
			height: 55,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 52,
			position: { x: 200, y: 2265 },
			data: { label: $LL.fields.baramij.dawah_title() },
			width: 80,
			height: 55,
			bgColor: '#FFB2E6',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 53,
			position: { x: 1, y: 2250 },
			data: {
				label: $LL.fields.baramij.dawah_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2E6',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 54,
			position: { x: 200, y: 2345 },
			data: { label: $LL.fields.baramij.nisa_title() },
			width: 80,
			height: 60,
			bgColor: '#FFB2DA',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 55,
			position: { x: 1, y: 2340 },
			data: {
				label: $LL.fields.baramij.nisa_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2DA',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 56,
			position: { x: 200, y: 2435 },
			data: { label: $LL.fields.baramij.atfal_title() },
			width: 80,
			height: 60,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 57,
			position: { x: 1, y: 2430 },
			data: {
				label: $LL.fields.baramij.atfal_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2CE',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 58,
			position: { x: 200, y: 2525 },
			data: { label: $LL.fields.baramij.zawjiyyah_title() },
			width: 80,
			height: 60,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 59,
			position: { x: 1, y: 2520 },
			data: {
				label: $LL.fields.baramij.zawjiyyah_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 60,
			position: { x: 200, y: 2615 },
			data: { label: $LL.fields.baramij.tarbiyah_title() },
			width: 80,
			height: 60,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 61,
			position: { x: 1, y: 2610 },
			data: {
				label: $LL.fields.baramij.tarbiyah_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 62,
			position: { x: 200, y: 2705 },
			data: { label: $LL.fields.baramij.aswat_title() },
			width: 80,
			height: 60,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 63,
			position: { x: 1, y: 2700 },
			data: {
				label: $LL.fields.baramij.aswat_content(),
			},
			width: 175,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
	]

	$: initialEdgesMobile = [
		{
			id: 'e1-2',
			source: 1,
			target: 2,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.1',
			source: 2,
			target: 3.1,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.2',
			source: 2,
			target: 3.2,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.3',
			source: 2,
			target: 3.3,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-4',
			source: 1,
			target: 4,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e4-5',
			source: 4,
			target: 5,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-6',
			source: 1,
			target: 6,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e6-7',
			source: 6,
			target: 7,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-8',
			source: 1,
			target: 8,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e8-9.1',
			source: 8,
			target: 9.1,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e8-9.2',
			source: 8,
			target: 9.2,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-10',
			source: 1,
			target: 10,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e10-11',
			source: 10,
			target: 11,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// END FARD, START QURAN
		{
			id: 'e12-13',
			source: 12,
			target: 13,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-15',
			source: 12,
			target: 15,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-17',
			source: 12,
			target: 17,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e13-14',
			source: 13,
			target: 14,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e15-16',
			source: 15,
			target: 16,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e17-18',
			source: 17,
			target: 18,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// HADITH
		{
			id: 'e19-20',
			source: 19,
			target: 20,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-22',
			source: 19,
			target: 22,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-24',
			source: 19,
			target: 24,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e20-21',
			source: 20,
			target: 21,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e22-23',
			source: 22,
			target: 23,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e24-25',
			source: 24,
			target: 25,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		//
		{
			id: 'e26-27',
			source: 26,
			target: 27,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// FIQH
		{
			id: 'e28-29',
			source: 28,
			target: 29,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-31',
			source: 28,
			target: 31,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-33',
			source: 28,
			target: 33,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-35',
			source: 28,
			target: 35,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e29-30',
			source: 29,
			target: 30,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e31-32',
			source: 31,
			target: 32,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e33-34',
			source: 33,
			target: 34,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e35-36',
			source: 35,
			target: 36,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// TASAWWUF
		{
			id: 'e37-38',
			source: 37,
			target: 38,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e37-40',
			source: 37,
			target: 40,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e38-39',
			source: 38,
			target: 39,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e40-41',
			source: 40,
			target: 41,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// ARABIYAH
		{
			id: 'e42-43',
			source: 42,
			target: 43,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-45',
			source: 42,
			target: 45,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-47',
			source: 42,
			target: 47,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-49',
			source: 42,
			target: 49,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e43-44',
			source: 43,
			target: 44,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e45-46',
			source: 45,
			target: 46,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e47-48',
			source: 47,
			target: 48,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e49-50',
			source: 49,
			target: 50,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// VARIOUS
		{
			id: 'e51-52',
			source: 51,
			target: 52,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-54',
			source: 51,
			target: 54,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-56',
			source: 51,
			target: 56,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-58',
			source: 51,
			target: 58,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-60',
			source: 51,
			target: 60,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-62',
			source: 51,
			target: 62,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e52-53',
			source: 52,
			target: 53,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e54-55',
			source: 54,
			target: 55,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e56-57',
			source: 56,
			target: 57,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e58-59',
			source: 58,
			target: 59,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e60-61',
			source: 60,
			target: 61,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e62-63',
			source: 62,
			target: 63,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
	]

	$: initialNodesDesktop = [
		{
			id: 1,
			position: { x: 770, y: 330 },
			data: { label: $LL.fields.fard.title() },
			width: 125,
			height: 80,
			bgColor: '#61FFA3',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 2,
			position: { x: 500, y: 75 },
			data: { label: $LL.fields.fard.tawhid_title() },
			width: 160,
			height: 55,
			bgColor: '#EBBAB9',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EBBAB9',
		},
		{
			id: 3.1,
			position: { x: 1, y: 0 },
			data: {
				label: $LL.fields.fard.tawhid_content1(),
			},

			width: 400,
			height: 60,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 3.2,
			position: { x: 1, y: 75 },
			data: {
				label: $LL.fields.fard.tawhid_content2(),
			},
			width: 400,
			height: 60,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 3.3,
			position: { x: 1, y: 150 },
			data: {
				label: $LL.fields.fard.tawhid_content3(),
			},
			width: 400,
			height: 60,
			bgColor: '#EBBAB9',
			borderColor: '#EBBAB9',
			targetPosition: 'right',
		},
		{
			id: 4,
			position: { x: 500, y: 240 },
			data: { label: $LL.fields.fard.tajwid_title() },
			width: 160,
			height: 55,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 5,
			position: { x: 1, y: 240 },
			data: {
				label: $LL.fields.fard.tajwid_content(),
			},
			width: 400,
			height: 60,
			bgColor: '#A2FDFF',
			borderColor: '#A2FDFF',
			targetPosition: 'right',
		},
		{
			id: 6,
			position: { x: 500, y: 340 },
			data: { label: $LL.fields.fard.ibadat_title() },
			width: 160,
			height: 55,
			bgColor: '#A7B7FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A7B7FF',
		},
		{
			id: 7,
			position: { x: 1, y: 330 },
			data: {
				label: $LL.fields.fard.ibadat_content(),
			},
			width: 400,
			height: 75,
			bgColor: '#A7B7FF',
			borderColor: '#A7B7FF',
			targetPosition: 'right',
		},
		{
			id: 8,
			position: { x: 500, y: 475 },
			data: { label: $LL.fields.fard.muamalat_title() },
			width: 160,
			height: 55,
			bgColor: '#FFC5A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 9.1,
			position: { x: 1, y: 440 },
			data: {
				label: $LL.fields.fard.muamalat_content1(),
			},
			width: 400,
			height: 60,
			bgColor: '#FFC5A7',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 9.2,
			position: { x: 1, y: 515 },
			data: {
				label: $LL.fields.fard.muamalat_content2(),
			},
			width: 400,
			height: 60,
			bgColor: '#FFC5A7',
			targetPosition: 'right',
			borderColor: '#FFC5A7',
		},
		{
			id: 10,
			position: { x: 500, y: 600 },
			data: { label: $LL.fields.fard.tasawwuf_title() },
			width: 160,
			height: 55,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 11,
			position: { x: 1, y: 600 },
			data: {
				label: $LL.fields.fard.tasawwuf_content(),
			},
			width: 400,
			height: 60,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		// END FARD, START QURAN
		{
			id: 12,
			position: { x: 770, y: 840 },
			data: { label: $LL.fields.quran.title() },
			width: 125,
			height: 90,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 13,
			position: { x: 500, y: 768 },
			data: { label: $LL.fields.fard.tajwid_title() },
			width: 160,
			height: 55,
			bgColor: '#A2FDFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 14,
			position: { x: 1, y: 760 },
			data: {
				label: $LL.fields.quran.tajwid_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#A2FDFF',
			targetPosition: 'right',
			borderColor: '#A2FDFF',
		},
		{
			id: 15,
			position: { x: 500, y: 858 },
			data: { label: $LL.fields.quran.tafsir_title() },
			width: 160,
			height: 55,
			bgColor: '#97D9FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 16,
			position: { x: 1, y: 850 },
			data: {
				label: $LL.fields.quran.tafsir_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#97D9FF',
			targetPosition: 'right',
			borderColor: '#97D9FF',
		},
		{
			id: 17,
			position: { x: 500, y: 948 },
			data: { label: $LL.fields.quran.ulum_title() },
			width: 160,
			height: 55,
			bgColor: '#97BFFF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		{
			id: 18,
			position: { x: 1, y: 940 },
			data: {
				label: $LL.fields.quran.ulum_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#97BFFF',
			targetPosition: 'right',
			borderColor: '#97BFFF',
		},
		// HADITH
		{
			id: 19,
			position: { x: 770, y: 1195 },
			data: { label: $LL.fields.hadith.title() },
			width: 125,
			height: 80,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 20,
			position: { x: 500, y: 1212 },
			data: { label: $LL.fields.hadith.ulum_title() },

			width: 160,
			height: 60,
			bgColor: '#00DF65',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 21,
			position: { x: 1, y: 1200 },
			data: {
				label: $LL.fields.hadith.ulum_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#00DF65',
			targetPosition: 'right',
			borderColor: '#00DF65',
		},
		{
			id: 22,
			position: { x: 500, y: 1100 },
			data: { label: $LL.fields.hadith.main_title() },
			width: 160,
			height: 60,
			sourcePosition: 'left',
			targetPosition: 'right',
			bgColor: '#00DF35',
			borderColor: '#00DF35',
		},
		{
			id: 23,
			position: { x: 1, y: 1100 },

			data: {
				label: $LL.fields.hadith.main_content(),
			},
			width: 400,
			height: 70,
			targetPosition: 'right',
			bgColor: '#00DF35',
			borderColor: '#00DF35',
		},
		//
		{
			id: 24,
			position: { x: 500, y: 1312 },
			data: { label: $LL.fields.hadith.seerah_title() },
			width: 160,
			height: 60,
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#00DF89',
			bgColor: '#00DF89',
		},
		{
			id: 25,
			position: { x: 1, y: 1300 },
			data: {
				label: $LL.fields.hadith.seerah_content(),
			},
			width: 400,
			height: 70,
			borderColor: '#00DF89',
			bgColor: '#00DF89',
			targetPosition: 'right',
		},
		// AQIDA
		{
			id: 26,
			position: { x: 770, y: 1488 },
			data: { label: $LL.fields.aqidah.title() },
			width: 125,
			height: 55,
			bgColor: '#D7D5A2',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 27,
			position: { x: 1, y: 1480 },
			data: {
				label: $LL.fields.aqidah.explanation(),
			},
			width: 400,
			height: 85,
			bgColor: '#D7D5A2',
			targetPosition: 'right',
			borderColor: '#D7D5A2',
		},
		// FIQH
		{
			id: 28,
			position: { x: 770, y: 1790 },
			data: { label: $LL.fields.fiqh.title() },
			width: 125,
			height: 80,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 29,
			position: { x: 500, y: 1658 },
			data: { label: $LL.fields.fiqh.furu_title() },
			width: 160,
			height: 55,
			bgColor: '#FFE8A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 30,
			position: { x: 1, y: 1650 },
			data: {
				label: $LL.fields.fiqh.furu_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFE8A7',
			targetPosition: 'right',
			borderColor: '#FFE8A7',
		},
		{
			id: 31,
			position: { x: 500, y: 1758 },
			data: { label: $LL.fields.fiqh.usul_title() },
			width: 160,
			height: 55,
			bgColor: '#FFDEA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 32,
			position: { x: 1, y: 1750 },
			data: {
				label: $LL.fields.fiqh.usul_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFDEA7',
			targetPosition: 'right',
			borderColor: '#FFDEA7',
		},
		{
			id: 33,
			position: { x: 500, y: 1858 },
			data: { label: $LL.fields.fiqh.qawaid_title() },
			width: 160,
			height: 55,
			bgColor: '#FFD3A7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 34,
			position: { x: 1, y: 1850 },
			data: {
				label: $LL.fields.fiqh.qawaid_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFD3A7',
			targetPosition: 'right',
			borderColor: '#FFD3A7',
		},
		{
			id: 35,
			position: { x: 500, y: 1958 },
			data: { label: $LL.fields.fiqh.adillah_title() },
			width: 160,
			height: 55,
			bgColor: '#FFCAA7',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		{
			id: 36,
			position: { x: 1, y: 1950 },
			data: {
				label: $LL.fields.fiqh.adillah_content(),
			},
			width: 400,
			height: 85,
			bgColor: '#FFCAA7',
			targetPosition: 'right',
			borderColor: '#FFCAA7',
		},
		// TASAWWUF
		{
			id: 37,
			position: { x: 770, y: 2220 },
			data: { label: $LL.fields.tasawwuf.title() },
			width: 125,
			height: 80,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 38,
			position: { x: 500, y: 2172 },
			data: { label: $LL.fields.tasawwuf.suluk_title() },
			width: 160,
			height: 55,
			bgColor: '#EEFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 39,
			position: { x: 1, y: 2150 },
			data: {
				label: $LL.fields.tasawwuf.suluk_content(),
			},
			width: 400,
			height: 100,
			bgColor: '#EEFFB2',
			targetPosition: 'right',
			borderColor: '#EEFFB2',
		},
		{
			id: 40,
			position: { x: 500, y: 2290 },
			data: { label: $LL.fields.tasawwuf.irfan_title() },
			width: 160,
			height: 55,
			bgColor: '#DDFFB2',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		{
			id: 41,
			position: { x: 1, y: 2280 },
			data: {
				label: $LL.fields.tasawwuf.irfan_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#DDFFB2',
			targetPosition: 'right',
			borderColor: '#DDFFB2',
		},
		// ARABIYAH
		{
			id: 42,
			position: { x: 770, y: 2650 },
			data: { label: $LL.fields.arabayyiah.title() },
			width: 125,
			height: 80,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 43,
			position: { x: 500, y: 2508 },
			data: { label: $LL.fields.arabayyiah.nahw_title() },
			width: 160,
			height: 70,
			bgColor: '#ECB2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 44,
			position: { x: 1, y: 2500 },
			data: {
				label: $LL.fields.arabayyiah.nahw_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#ECB2FF',
			targetPosition: 'right',
			borderColor: '#ECB2FF',
		},
		{
			id: 45,
			position: { x: 500, y: 2608 },
			data: { label: $LL.fields.arabayyiah.sarf_title() },
			width: 160,
			height: 70,
			bgColor: '#E2B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 46,
			position: { x: 1, y: 2600 },
			data: { label: $LL.fields.arabayyiah.sarf_content() },
			width: 400,
			height: 70,
			bgColor: '#E2B2FF',
			targetPosition: 'right',
			borderColor: '#E2B2FF',
		},
		{
			id: 47,
			position: { x: 500, y: 2708 },
			data: { label: $LL.fields.arabayyiah.balaghah_title() },
			width: 160,
			height: 70,
			bgColor: '#D5B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 48,
			position: { x: 1, y: 2700 },
			data: {
				label: $LL.fields.arabayyiah.balaghah_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#D5B2FF',
			targetPosition: 'right',
			borderColor: '#D5B2FF',
		},
		{
			id: 49,
			position: { x: 500, y: 2800 },
			data: { label: $LL.fields.arabayyiah.natiq_title() },
			width: 160,
			height: 70,
			bgColor: '#C6B2FF',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		{
			id: 50,
			position: { x: 1, y: 2800 },
			data: {
				label: $LL.fields.arabayyiah.natiq_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#C6B2FF',
			targetPosition: 'right',
			borderColor: '#C6B2FF',
		},
		// VARIOUS
		{
			id: 51,
			position: { x: 770, y: 3250 },
			data: { label: $LL.fields.baramij.title() },
			width: 125,
			height: 80,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			borderColor: 'black',
		},
		{
			id: 52,
			position: { x: 500, y: 3000 },
			data: { label: $LL.fields.baramij.dawah_title() },
			width: 160,
			height: 70,
			bgColor: '#FFB2E6',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 53,
			position: { x: 1, y: 3000 },
			data: {
				label: $LL.fields.baramij.dawah_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFB2E6',
			targetPosition: 'right',
			borderColor: '#FFB2E6',
		},
		{
			id: 54,
			position: { x: 500, y: 3100 },
			data: { label: $LL.fields.baramij.nisa_title() },
			width: 160,
			height: 85,
			bgColor: '#FFB2DA',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 55,
			position: { x: 1, y: 3100 },
			data: {
				label: $LL.fields.baramij.nisa_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFB2DA',
			targetPosition: 'right',
			borderColor: '#FFB2DA',
		},
		{
			id: 56,
			position: { x: 500, y: 3205 },
			data: { label: $LL.fields.baramij.atfal_title() },
			width: 160,
			height: 85,
			bgColor: '#FFB2CE',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 57,
			position: { x: 1, y: 3200 },
			data: {
				label: $LL.fields.baramij.atfal_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFB2CE',
			targetPosition: 'right',
			borderColor: '#FFB2CE',
		},
		{
			id: 58,
			position: { x: 500, y: 3305 },
			data: { label: $LL.fields.baramij.zawjiyyah_title() },
			width: 160,
			height: 85,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 59,
			position: { x: 1, y: 3300 },
			data: {
				label: $LL.fields.baramij.zawjiyyah_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 60,
			position: { x: 500, y: 3405 },
			data: { label: $LL.fields.baramij.tarbiyah_title() },
			width: 160,
			height: 70,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 61,
			position: { x: 1, y: 3400 },
			data: {
				label: $LL.fields.baramij.tarbiyah_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 62,
			position: { x: 500, y: 3505 },
			data: { label: $LL.fields.baramij.aswat_title() },
			width: 160,
			height: 70,
			bgColor: '#FFB2C3',
			sourcePosition: 'left',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
		{
			id: 63,
			position: { x: 1, y: 3500 },
			data: {
				label: $LL.fields.baramij.aswat_content(),
			},
			width: 400,
			height: 70,
			bgColor: '#FFB2C3',
			targetPosition: 'right',
			borderColor: '#FFB2C3',
		},
	]

	$: initialEdgesDesktop = [
		{
			id: 'e1-2',
			source: 1,
			target: 2,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.1',
			source: 2,
			target: 3.1,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.2',
			source: 2,
			target: 3.2,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e2-3.3',
			source: 2,
			target: 3.3,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-4',
			source: 1,
			target: 4,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e4-5',
			source: 4,
			target: 5,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-6',
			source: 1,
			target: 6,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e6-7',
			source: 6,
			target: 7,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-8',
			source: 1,
			target: 8,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e8-9.1',
			source: 8,
			target: 9.1,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e8-9.2',
			source: 8,
			target: 9.2,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e1-10',
			source: 1,
			target: 10,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e10-11',
			source: 10,
			target: 11,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// END FARD, START QURAN
		{
			id: 'e12-13',
			source: 12,
			target: 13,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-15',
			source: 12,
			target: 15,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e12-17',
			source: 12,
			target: 17,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e13-14',
			source: 13,
			target: 14,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e15-16',
			source: 15,
			target: 16,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e17-18',
			source: 17,
			target: 18,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// HADITH
		{
			id: 'e19-20',
			source: 19,
			target: 20,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-22',
			source: 19,
			target: 22,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e19-24',
			source: 19,
			target: 24,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e20-21',
			source: 20,
			target: 21,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e22-23',
			source: 22,
			target: 23,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e24-25',
			source: 24,
			target: 25,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		//
		{
			id: 'e26-27',
			source: 26,
			target: 27,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// FIQH
		{
			id: 'e28-29',
			source: 28,
			target: 29,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-31',
			source: 28,
			target: 31,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-33',
			source: 28,
			target: 33,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e28-35',
			source: 28,
			target: 35,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e29-30',
			source: 29,
			target: 30,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e31-32',
			source: 31,
			target: 32,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e33-34',
			source: 33,
			target: 34,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e35-36',
			source: 35,
			target: 36,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// TASAWWUF
		{
			id: 'e37-38',
			source: 37,
			target: 38,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e37-40',
			source: 37,
			target: 40,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e38-39',
			source: 38,
			target: 39,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e40-41',
			source: 40,
			target: 41,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// ARABIYAH
		{
			id: 'e42-43',
			source: 42,
			target: 43,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-45',
			source: 42,
			target: 45,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-47',
			source: 42,
			target: 47,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e42-49',
			source: 42,
			target: 49,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e43-44',
			source: 43,
			target: 44,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e45-46',
			source: 45,
			target: 46,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e47-48',
			source: 47,
			target: 48,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e49-50',
			source: 49,
			target: 50,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		// VARIOUS
		{
			id: 'e51-52',
			source: 51,
			target: 52,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-54',
			source: 51,
			target: 54,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-56',
			source: 51,
			target: 56,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-58',
			source: 51,
			target: 58,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-60',
			source: 51,
			target: 60,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		{
			id: 'e51-62',
			source: 51,
			target: 62,
			noHandle: true,
			arrow: false,
			edgeColor: 'black',
		},
		//
		{
			id: 'e52-53',
			source: 52,
			target: 53,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e54-55',
			source: 54,
			target: 55,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e56-57',
			source: 56,
			target: 57,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e58-59',
			source: 58,
			target: 59,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e60-61',
			source: 60,
			target: 61,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
		{
			id: 'e62-63',
			source: 62,
			target: 63,
			noHandle: true,
			arrow: true,
			edgeColor: 'black',
		},
	]
</script>

<br><br>
<br>

<h1>{$LL.fields.title()}</h1>
{#if pageWidth < 450}
	<div id="tiny">
		<Svelvet width={320} height={2800} nodes={initialNodesTiny} edges={initialEdgesTiny} movement={false} />
	</div>
{:else if pageWidth < 1000}
	<div id="mobile">
		<Svelvet width={430} height={2800} nodes={initialNodesMobile} edges={initialEdgesMobile} movement={false} />
	</div>
{:else}
	<br />
	<div id="desktop">
		<Svelvet width={900} height={3700} nodes={initialNodesDesktop} edges={initialEdgesDesktop} movement={false} />
	</div>
{/if}

<style>
	div#tiny {
		width: 320px;
		margin: 1px auto;
	}
	div#mobile {
		width: 500px;
		margin: 5px auto;
	}
	div#desktop {
		width: 1000px;
		margin: 0 auto;
		/* border: 2px solid rgb(182, 255, 142); */
		border-radius: 12px;
	}
	h1 {
		text-align: center;
	}
	:global(div#desktop > div > div > div > .Node) {
		font-size: 20px !important; /* this should be a param in svelvet..... */
		font-family: "Cabin", "Scheherazade New", "adwa-assalaf", -apple-system,
		BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell,
		"Open Sans", "Helvetica Neue", sans-serif;
		line-height: 145%;
	}
	/* and mobile size gets the default, which is 14px in the library styles (file: Node/index.svelte) */
	:global(div#tiny > div > div > div > .Node) {
		font-size: 13px !important; /* this should be a param in svelvet..... */
		font-family: "Cabin", "Scheherazade New", "adwa-assalaf", -apple-system,
		BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell,
		"Open Sans", "Helvetica Neue", sans-serif;
		line-height: 130%;
	}
	@media only screen and (max-width: 500px) {
		div#mobile {
			width: 98vw;
			overflow: visible;
			border-radius: 12px;
		}
	}
</style>
