// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Knowledge & Insight
	 */
	title: string
	/**
	 * The Center For
	 */
	center: string
	/**
	 * ltr
	 */
	direction: string
	coursePage: {
		/**
		 * About this course
		 */
		about: string
	}
	hero: {
		/**
		 * Islamic Knowledge, Prophetic Spirituality
		 */
		header1: string
		/**
		 * Complete Islamic Knowledge Taught by Scholars
		 */
		subheader1: string
	}
	about: {
		/**
		 * About
		 */
		title: string
	}
	welcome: {
		/**
		 * Begin or continue your studies with our complete curriculum covering all the religious sciences
		 */
		complete_curriculum: string
		/**
		 * Our mission is to link students to true scholars, who connect them to the Noble Prophet (ﷺ).
		 */
		mission: string
		/**
		 * Access your lessons and recordings wherever you are—learning always goes on.
		 */
		online: string
		/**
		 * Benefit now from the library of articles and videos that will continue tog row inshaAllah
		 */
		articles: string
	}
	shaykh: {
		/**
		 * Supervisor
		 */
		heading: string
		/**
		 * Honorable Shaykh Abd al-Rahman al-Sha'ar
		 */
		subheading: string
		/**
		 * Shaykh Abd al-Rahman al-Sha’ar began seeking knowledge at a young age, being nurtured by scholars and those who love knowledge. He dedicated his life to the service of Islam and studied complete curriculums in all its areas, including: Quran, Hadith, Fiqh, Aqida, Tasawwuf, Arabic and its sciences, and more. He received all this divine knowledge at the hands of lordly scholars, attaining full license to teach all the inner and the outer religious sciences from many of the top scholars of the past century. Today, he dedicates himself to producing both books  and inheritors of the highest standard.
		 */
		short_bio: string
		/**
		 * Learn more about the Shaykh
		 */
		button: string
		/**
		 * Short Biography
		 */
		long_bio_title: string
		/**
		 * His Studies
		 */
		long_bio_studies_title: string
		/**
		 * Shaykh ʿAbd al-Raḥmān began seeking knowledge and memorizing the noble Qur’an in Masjid al-Ashmar and Masjid Zayd b. Thābit. He then entered Maʿhad al-Fatḥ al-Islāmī and graduated with honors. He would attend the classes of a number of great scholars in Syria, such as Shaykh ʿAbd al-Razzāq al-Ḥalabī’s morning lessons in the Umayyad Mosque, Shaykh Khalīl al-Ṣabbāgh’s lessons in Masjid Ward al-Kabīr, and the erudite Shaykh Usāma al-Rifāʿī’s classes in the Masjid of ʿAbd al-Karīm al-Rifāʿī. He memorized parts of the Qur’an under the tutelage of Shaykh Shukrī al-Luḥafī and Shaykh Muḥammad al-Sayyid Ismāʿīl Abū Munīr.
		 */
		long_bio_studies_1: string
		/**
		 * Shaykh ʿAbd al-Raḥmān attended the lessons of Shaykh Muḥammad Jumuʿa for ten years and studied many books with him in various sciences in Maʿhad al-Fatḥ as well as outside of it. Among the books Shaykh ʿAbd al-Raḥmān read in Ḥanafī fiqh are: Marāqī al-Falāḥ, al-Ikhtiyār li-Taʿlīl al-Mukhtār, two-thirds of Ḥāshiyat Ibn ʿĀbidīn, some of Sharḥ al-Jaṣṣāṣ ʿalá Mukhtaṣar al-Ṭahāwī, Badā’iʿ al-Ṣanā’iʿ, Sharḥ al-Taṣrīḥ ʿalá al-Tawḍīḥ, and Tafsīr al-Nasafī. Shaykh ʿAbd al-Raḥmān also read al-Aṣl: Mabsūṭ al-Imām Muḥammad and al-Lubāb: Sharḥ al-Kitāb by himself and reviewed more difficult passages with Shaykh Muḥammad Jumuʿa. 
		 */
		long_bio_studies_2: string
		/**
		 * He attended the lessons of Shaykh Muḥammad Shuqayr in Masjid al-Ḥasan and studied many works with him, such as al-Risāla al-Qushayriyya, Sunan Abī Dāwūd, al-Jāmiʿ by al-Tirmidhī, Sharḥ Ibn ʿAqīl, al-Nahw al-Wāḍiḥ, Iḥyā’ ʿUlūm al-Dīn, al-Adhkār, and Sharḥ al-Nawawī ʿalá Ṣaḥīḥ Muslim. Shaykh ʿAbd al-Raḥmān attended the lessons of the erudite scholar Shaykh Muḥammad Abū al-Hudá al-Yaʿqūbī, studying with him Sharḥ Umm al-Barāhīn by al-Sanūsī in the Umayyad Mosque and Qawā’id al-Taṣawwuf in the Masjid of Muḥyī al-Dīn b. al-ʿArabī. He attended the lessons of Shaykh Muḥammad Asʿad al-Ṣāgharjī, reading with him Sharḥ al-Mabāḥith al-Aṣliyya by ibn ʿAjība and al-Fatḥ al-Rabbāni by Shaykh ʿAbd al-Qādir al-Jīlānī. He also attended the lessons of Shaykh Ḥassān al-Hindī, read with him at Maʿhad al-Fatḥ and after graduating, and benefitted greatly from him. He read Ṣaḥīḥ al-Bukhārī with Shaykh Naʿīm ʿAraqsūsī. Shaykh ʿAbd al-Raḥmān attended the gatherings of ḥadīth held by Shaykh ʿUmar Nashūqātī in Masjid al-Ḥājibiyya, studied other sciences, and read several books with him, including al-Adab al-Mufrad by al-Bukhārī, al-Muwaṭṭa’ by Imam Mālik, al-Āthār by Imam Muḥammad, and the Shamā’il of Imam al-Tirmidhī.
		 */
		long_bio_studies_3: string
		/**
		 * His Spiritual Path and Taṣawwuf
		 */
		long_bio_spirituality_title: string
		/**
		 * Shaykh ʿAbd al-Raḥmān grew up under the nurturing wing of Shaykh ʿAbd al-Raḥmān al-Shāghūrī as his father took him to the public and private lessons of the shaykh. Shaykh ʿAbd al-Raḥmān adored Shaykh al-Shāghūrī from a young age; the latter would consistently go out of his way for Shaykh ʿAbd al-Raḥmān until God took back Shaykh al-Shāghūrī’s soul in 2004, when Shaykh ʿAbd al-Raḥmān was only eighteen years old. Consequently, Shaykh ʿAbd al-Raḥmān continued the path of taṣawwuf under the guidance of Shaykh Muṣṭafá al-Turkmānī, consistently attending and recording his lessons for seven years until the shaykh’s passing. Shaykh ʿAbd al-Raḥmān then completed the path under the guidance of Shaykh Shukrī al-Luḥafī; upon his instruction, Shaykh ʿAbd al-Raḥmān entered spiritual seclusion (khalwa). He was also the head singer at Shaykh Shukrī’s public and private gatherings, accompanying him for several years.
		 */
		long_bio_spirituality_1: string
		/**
		 * Afterwards, Shaykh Muḥammad Amīn al-Fārūqī requested that Shaykh ʿAbd al-Raḥmān enter spiritual seclusion under him; thereafter, he specially authorized Shaykh ʿAbd al-Raḥmān in the path to give spiritual guidance, enter others into spiritual seclusions, and prescribe the Singular Name [i.e., a spiritual practice involving repetition of the name ‘Allāh’].
		 */
		long_bio_spirituality_2: string
		/**
		 * Shaykh ʿAbd al-Raḥmān then entered another spiritual seclusion under Shaykh ʿAbd al-Bāqī Miftāḥ al-Jazā’irī, who also authorized him in the path, and then with Shaykh Ḥasan al-Anṣārī al-Jazā’irī, who would authorize him as well. Among the greats he benefitted most from in the arena of experiential Sufism was Shaykh Kamāl al-Ḥusaynī al-Shamīsātī, one of the students of Shaykh Muḥammad al-Hāshimī.
		 */
		long_bio_spirituality_3: string
	}
	goals: {
		/**
		 * Spreading the inner and outer sciences as Imam al-Ghazali accomplished – Allah be pleased with him.
		 */
		'1': string
		/**
		 * Perfecting the reading of the Noble Quran in recitation and tajwid, with a linked chain of ascription and ijaza certification in the Ten Readings – all upon the way the noble Companions received the Quran from the Prophet – peace and blessings upon him –along with reviving the role of the Quran in Muslims’ souls.
		 */
		'2': string
		/**
		 * Reviving the service of the Prophetic Sunnah and the noble Science of Hadith in both narration and understanding. Furthermore, resetting the compass of the Ummah towards following the guidance of the Prophet – Allah send peace and blessings upon him – and also his biography (Sirah), so that the Ummah can gain peace and be saved.
		 */
		'3': string
		/**
		 * Explaining the obligatory knowledge every Muslim man and woman must know—for a slave of Allah to worship his Lord upon based guidance and be free of sins based on his ignorance of that.
		 */
		'4': string
		/**
		 * Teaching the correct beliefs of the righteous predecessors (Salaf). This is done through the Sunni method as demonstrated in the beliefs of the Ashʿari, Maturidi, and Athar approaches, along with the understanding of the lordly scholars and knowers of the Ummah.
		 */
		'5': string
		/**
		 * Explaining the detailed rulings of the Divine law of Allah (Shariʿa) in accordance with the Four Imams – Allah be pleased upon them. Thus, a Muslim can apply his religion correctly in accordance with the pure Sharia, and his actions can be built upon Fiqh and sound knowledge, allowing one to worship Allah Almighty based upon guidance and leave the prison of ignorance and the forbidden..
		 */
		'6': string
		/**
		 * Spreading the correct spirituality (tasawwuf) which is the soul of the religion, what’s been named ihsan. This includes both spiritual seeking and enlightened understanding. This is for a Muslim to leave all sins and follow the way of the Master of All Creation in worshipping His lord with witnessing and awareness that he himself is being witnessed, which leads to complete inheritance and following.
		 */
		'7': string
		/**
		 * Teaching the Arabic language, the language of the Quan and the Beloved Prophet – peace and blessings upon him. This is to correctly understand the words of Allah Almighty and the purified prophetic Sunnah, and the words of the scholars. Indeed, it has been said: “Whoever does not perfect the Arabic language, is not trusted in his knowledge.”
		 */
		'8': string
		/**
		 * Perfecting the tool-sciences such as rhetoric (maʿani), expression (bayan), linguistic devices (badiʿ), etymology (sarf), grammar (nahw), poetic meters, and logic. A student of knowledge needs all of them in order to completely absorb knowledge and then present it in the best way possible.
		 */
		'9': string
		/**
		 * Training in dawah, public speaking and poetry skills, all of which are essential in benefitting others, through an approach where one can express things in a clear, convincing, and moving way.
		 */
		'10': string
		/**
		 * Our goal
		 */
		goal: string
		/**
		 * Reviving the religious sciences by
		 */
		title: string
	}
	wisdoms: {
		/**
		 * Supervisor's Wisdoms
		 */
		title: string
		list: {
			/**
			 * The truly joyous don't strive for ijazats and certificates
			 */
			ijaza_1: string
		}
	}
	articles: {
		/**
		 * Articles
		 */
		title: string
		knowledge_good_intentions: {
			/**
			 * Good Intentions – Advice for Students of Knowledge 1
			 */
			title: string
			/**
			 * ترجمة الوصايا لطالب العلم الوصية الأولى\nAdvice for Students of Knowledge
		Advice 1: Good Intentions\nThe Prophet, peace and blessings be upon him, said, “Actions are only by intention, and for every man is only what he intended.”\nThe first obligation upon a student of knowledge is to make a good intention for his knowledge and teaching. A good, sincere intention is the greatest of elixirs — the good and benefit of an action is multiplied in accordance with the plentitude of intentions.
		Some the intentions that a student of knowledge should have are the following:\n- Preservation of the Book of Allah and the Sunnah of His Messenger, peace and blessings be upon him\n- Obedience to the command of the Beloved, peace and blessings be upon him\n- Listening to and transmitting the speech of the Messenger of Allah, peace and blessings be upon him\n- Lifting sins from oneself and fellow Muslims by learning and teaching the personal and communal obligations\n- Exposure to the winds of Divine Mercy in order to attain His pleasure\n- Remembrance and reminder\n- Preserving one’s time \n- Spreading the sacred teachings of Islam \n- I`tikāf (religious seclusion) if the gathering is in the mosque \n- Renewal of faith\n- Mutual assistance to piety,  mindfulness of God, commanding the good, and forbidding the evil\n- Increasing the collective body of the people of good \n- Seeking the mercy of Allah to descend by remembering the righteous\n- Purification of the inward and struggling against the lower self\n- Acting according to one’s knowledge Oh Allah, make our knowledge, actions, teaching, and the rest of our actions sincere for Your Noble Countenance, by the rank of Your Greatest Beloved, peace and blessings be upon him and his beloveds.\n A servant of this noble knowledge,\nAbd al-Rahman al-Sha`ār\n02/21/19
			 */
			content: string
		}
	}
	tags: {
		/**
		 * Obligatory Knowledge
		 */
		fard: string
		/**
		 * The Prophet said - Allah bless him and send him peace: "Seeking knowledge is mandatory upon every Muslim." The Scholars have explained that this obligatory knowledge on every Muslim man and women are five: Beliefs, Tajwid to correct what is recited in Salah, Fiqh of Worship & Interactions, and Purification of the soul.
		 */
		fard_explanation: string
		/**
		 * Beliefs
		 */
		aqidah: string
		/**
		 * Truly, Beliefs is the most noble religious science. It is the bedrock of all obligations, and the foundation of all commands—because it is linked to the Divine Being. This is why it's mandatory for every Muslim to learn what will correct his beliefs, as Allah Almighty said: "And I have not created jinn or human beings except to worship Me." [51:56] Ibn Jurayj explained: "That means: 'To know Me.'"
		 */
		aqidah_explanation: string
		/**
		 * Seerah & Shamail
		 */
		sirah: string
		/**
		 * Works of Prophetic Biography & Description give out rays of light, the light of Islamic principles and lofty ettiqutte. It is what allows one to udnerstand the book of Allah Almighty and its goals. Surely the Prophet (peace and blessings upon him) is the practical example of all that is in the Quran, as Lady Aisha (Allah be pleased upon her) said: 'His ettiquette was the Quran.'
		 */
		sirah_explanation: string
		/**
		 * Assorted Programs
		 */
		program: string
		program_explanation: string
		/**
		 * Arabic for Non-natives
		 */
		natiq: string
		/**
		 * After learning the knowledge obligatory upon every Muslim, learning Arabic for non-Arabs is a life-changing improvement, allowing them to understand the Quran, Sunnah, and Scholars directly without any barrier.
		 */
		natiq_explanation: string
		/**
		 * Various Courses
		 */
		misc: string
		/**
		 * Various Courses
		 */
		misc_explanation: string
		/**
		 * Quran Recitation & Tajwid
		 */
		tajwid: string
		/**
		 * Theoretical
		 */
		tajwid_nazari: string
		/**
		 * Practical
		 */
		tajwid_amali: string
		/**
		 * Truly the science of Tajwid is part of the knowledge obligatory for every Muslim to learn – to the extent by which Salah is valid. The goal of Tajwid is giving the Quran and each letter in it its right, and to recite as the Prophet (peace and blessings upon him) recited.
		 */
		tajwid_explanation: string
		/**
		 * Arabic & Its Sciences
		 */
		arabi: string
		/**
		 * Nahw
		 */
		arabi_nahw: string
		/**
		 * Sarf
		 */
		arabi_sarf: string
		/**
		 * Balaghah
		 */
		arabi_balaghah: string
		/**
		 * "Indeed Allah Almighty honored the Arabic language out of all others, by making it the vessel for His Noble Book and the Sunnah of His Prophet - Allah send blessings and peace upon him - the Almighty said: "We have sent it down as an Arabic Quran so that you may understand" [Yusuf: 2]. Thus, it is the tongue of the clear Divine law and it's study is widespread and an inseparable part of the religion."
		 */
		arabi_explanation: string
		/**
		 * Fiqh & Its Foundations
		 */
		fiqh: string
		/**
		 * Rulings
		 */
		fiqh_rulings: string
		/**
		 * Foundations
		 */
		fiqh_foundations: string
		/**
		 * Principles
		 */
		fiqh_principles: string
		/**
		 * Evidences
		 */
		fiqh_evidences: string
		/**
		 * Truly Fiqh is one of the noblest and greatest religious sciences - after learning what corrects his belief. Indeed, Fiqh corrects a person's worship and interactions, allowing him to worship Allah upon guidance, getting to know Him in the worldy life upto the levels of the rigtheous, and in the afterlife upto the ranks of the best. Allah make us of them by His generosity and favor!
		 */
		fiqh_explanation: string
		/**
		 * Spirituality
		 */
		tasawwuf: string
		/**
		 * Self-purification & Suluk
		 */
		tasawwuf_suluk: string
		/**
		 * Higher Realities
		 */
		tasawwuf_irfan: string
		/**
		 * There is no doubt that Tasawwuf (Spirituality) is the most beneficial knowledge, because it is the way to clear the soul of its flaws and filth, and adorning it with higher truths and realities, and purifying it with precise and wonderful details. Thus it is the beneficial knowledge the fruit of which is fear of Allah Almighty. Real Spirituality is what makes clear the behavioural, nurturing and development method - and after that the spiritual. It is made up of three stages: cleansing, adorning and manifesting.
		 */
		tasawwuf_explanation: string
		/**
		 * The Quran & Its Sciences
		 */
		tafsir: string
		/**
		 * Ishari Tafsir
		 */
		tafsir_ishari: string
		/**
		 * External Tafsir
		 */
		tafsir_zahir: string
		/**
		 * Quran Sciences
		 */
		ulum_quran: string
		/**
		 * "Truly the Quran is the book of guidance for mankind, it guides them to the upright, and leads them to what is good for their worldly- and afterlife. Among the most important things a Muslim must be concerned about and focus on: reflecting on the Quran and understanding its meanings. That is the way to success in this life and the next, and this is not possible except by returning to what the Scholars of Tafsir have written about the Words of Allah Almighty."
		 */
		tafsir_explanation: string
		/**
		 * Hadith & Its Sciences
		 */
		hadith: string
		/**
		 * Hadith Texts
		 */
		hadith_texts: string
		/**
		 * Hadith Sciences
		 */
		hadith_sciences: string
		/**
		 * Surely the Prophetic Sunnah is the source of Islam and reviver of Iman in the hearts. Whoever reads these noble hadith is in the company of the Messenger of Allah (peace and blessings upon him), receiving knowledge and insight from him. And truly the scholars of Islam have precisely preserved all these narrations with the utmost excellence and clarity.
		 */
		hadith_explanation: string
		/**
		 * Assorted Classes
		 */
		other: string
		other_explanation: string
		/**
		 * Dawah & Outreach
		 */
		'public': string
	}
	courses: {
		/**
		 * Courses
		 */
		title: string
		'tajwid-qaida': {
			/**
			 * /books/tajwid-qaida.jpg
			 */
			src: string
			/**
			 * Tajwid: Level 1
			 */
			title: string
			/**
			 * A practical first text to reciting the Noble Quran correctly with tajwid
			 */
			desc: string
			/**
			 * Al-Qaida al-Nuraniyyah
			 */
			book: string
			explanation: string
		}
		'tajwid-hidayatrahman': {
			/**
			 * Tajwid: Level 2
			 */
			title: string
			desc: string
			/**
			 * /books/tajwid-hidayatrahman.jpg
			 */
			src: string
			/**
			 * Hidayat al-Rahman
			 */
			book: string
		}
		'tajwid-thani': {
			/**
			 * Tajwid: Level 3
			 */
			title: string
			/**
			 * Written by the expert scholar Yahya al-Ghawthani
			 */
			desc: string
			/**
			 * /books/tajwid-thani.jpg
			 */
			src: string
			/**
			 * Al-Mustawa al-Thani
			 */
			book: string
		}
		'tajwid-jazari': {
			/**
			 * Tajwid: Level 4
			 */
			title: string
			desc: string
			/**
			 * /books/tajwid-jazari.jpg
			 */
			src: string
			/**
			 * Sharh al-Jazariyyah
			 */
			book: string
		}
		'tajwid-amma': {
			/**
			 * Level 1: Open-book Recitation
			 */
			title: string
			/**
			 * Apply the rules of tajwid to these regularly read surah!
			 */
			desc: string
			/**
			 * /books/mushaf.jpg
			 */
			src: string
			/**
			 * Quran Juz 30: ʿAmma
			 */
			book: string
		}
		'tajwid-reading': {
			/**
			 * Level 2: Open-book Recitation
			 */
			title: string
			desc: string
			/**
			 * /books/mushaf.jpg
			 */
			src: string
			/**
			 * The Entire Quran
			 */
			book: string
		}
		'tajwid-reciting': {
			/**
			 * Level 3: Reciting from Memory
			 */
			title: string
			/**
			 * In all 10 recitations, depending on the student's aims
			 */
			desc: string
			/**
			 * /books/mushaf.jpg
			 */
			src: string
			/**
			 * The Entire Quran for Ijaza
			 */
			book: string
		}
		'fiqh-nur': {
			/**
			 * Fiqh of Worship: 1
			 */
			title: string
			/**
			 * Essential rules for a Muslim's worship and all things related to that
			 */
			desc: string
			/**
			 * /books/fiqh-nur.jpg
			 */
			src: string
			/**
			 * Nur al-Idah
			 */
			book: string
			explanation: string
		}
		'fiqh-quduri': {
			/**
			 * Fiqh of Interactions: 1
			 */
			title: string
			/**
			 * Essential rules for a Muslim's dealings  with Allah's creation and his relations
			 */
			desc: string
			/**
			 * /books/fiqh-quduri.jpg
			 */
			src: string
			/**
			 * Mukhtasar al-Quduri
			 */
			book: string
			explanation: string
		}
		'aqidah-ahl-sunnah': {
			/**
			 * Beliefs: Essentials
			 */
			title: string
			/**
			 * The obligatory beliefs for every Muslim in a brief and simple text
			 */
			desc: string
			/**
			 * /books/aqidah-ahl-sunnah.jpg
			 */
			src: string
			/**
			 * Aqida Ahl al-Sunnah
			 */
			book: string
			explanation: string
		}
		'tasawwuf-rawdah': {
			/**
			 * Spirituality: Introduction
			 */
			title: string
			/**
			 * The essential introduction to Ihsan in every part of life to get closer to Allah Almighty
			 */
			desc: string
			/**
			 * /books/tasawwuf-rawdah.jpg
			 */
			src: string
			/**
			 * Radwat al-Ushaq
			 */
			book: string
			explanation: string
		}
		'tasawwuf-tuhfah': {
			/**
			 * Spirituality: Essentials
			 */
			title: string
			/**
			 * Rectifying worship, regular actions, and repairing the bad traits of the heart
			 */
			desc: string
			/**
			 * /books/tasawwuf-tuhfah.jpg
			 */
			src: string
			/**
			 * Tuhfat al-Salikin
			 */
			book: string
			explanation: string
		}
		'tasawwuf-fuyud': {
			/**
			 * Spirituality: Essentials
			 */
			title: string
			/**
			 * A collection of commanding hadith, with explanations to help bring them to life
			 */
			desc: string
			/**
			 * /books/tasawwuf-fuyud.jpg
			 */
			src: string
			/**
			 * Al-Fuyud al-Ahmadiyyah
			 */
			book: string
			explanation: string
		}
		'program-youth': {
			/**
			 * A complete program spanning several books
			 */
			title: string
			/**
			 * This is placeholder of some text, we need to write later
			 */
			desc: string
			src: string
			/**
			 * Youth Program
			 */
			book: string
			explanation: string
		}
		'program-women': {
			/**
			 * A complete program spanning several books
			 */
			title: string
			/**
			 * This is placeholder of some text, we need to write later
			 */
			desc: string
			src: string
			/**
			 * Women's Program
			 */
			book: string
			explanation: string
		}
		'natiq-um1': {
			/**
			 * Preparatory Level
			 */
			title: string
			/**
			 * Starting from how to pronounce letters, all the way to communicating in everyday situations
			 */
			desc: string
			/**
			 * /books/natiq-um1.jpg
			 */
			src: string
			/**
			 * Silsilah al-Lisan: 1
			 */
			book: string
			explanation: string
		}
		'natiq-um2': {
			/**
			 * Beginner Level
			 */
			title: string
			/**
			 * Students begin learning a foundation in Arabic grammar and sentence construction.
			 */
			desc: string
			/**
			 * /books/natiq-um2.jpg
			 */
			src: string
			/**
			 * Silsilah al-Lisan: 2
			 */
			book: string
			explanation: string
		}
		'natiq-um3': {
			/**
			 * Intermediate Level
			 */
			title: string
			/**
			 * Learners start composing short essays, cover more topics for vocabulary, and expand their grammar.
			 */
			desc: string
			/**
			 * /books/natiq-um3.jpg
			 */
			src: string
			/**
			 * Silsilah al-Lisan: 3
			 */
			book: string
			explanation: string
		}
		'natiq-um4': {
			/**
			 * Advanced Level
			 */
			title: string
			/**
			 * Training to write long texts, dialogues and being able to handle any Arabic book or reference
			 */
			desc: string
			/**
			 * /books/natiq-um4.jpg
			 */
			src: string
			/**
			 * Silsilah al-Lisan: 4
			 */
			book: string
			explanation: string
		}
		'nahw-mabadi': {
			/**
			 * Level 1
			 */
			title: string
			desc: string
			src: string
			/**
			 * Mabadiʾ Durus al-Arabiyyah
			 */
			book: string
			explanation: string
		}
		'nahw-tawdih': {
			/**
			 * Level 1
			 */
			title: string
			desc: string
			src: string
			/**
			 * Al-Tawdih: Sharh al-Ajurumiyyah
			 */
			book: string
			explanation: string
		}
		'nahw-tashil': {
			/**
			 * Level 2
			 */
			title: string
			desc: string
			src: string
			/**
			 * Al-Tashil: Sharh al-Ajurumiyyah
			 */
			book: string
			explanation: string
		}
		'nahw-durus': {
			/**
			 * Level 3
			 */
			title: string
			desc: string
			src: string
			/**
			 * Durus Nahwiyya
			 */
			book: string
			explanation: string
		}
		'nahw-qatr': {
			/**
			 * Level 4
			 */
			title: string
			desc: string
			src: string
			/**
			 * Sharh Qatr al-Nada
			 */
			book: string
			explanation: string
		}
		'nahw-alfiyyah': {
			/**
			 * Level 5
			 */
			title: string
			desc: string
			src: string
			/**
			 * Al-Alfiyyah
			 */
			book: string
			explanation: string
		}
		'nahw-ibnaqil': {
			/**
			 * Level 6
			 */
			title: string
			desc: string
			src: string
			/**
			 * Sharh ibn Aqīl
			 */
			book: string
			explanation: string
		}
		'sarf-amthilah': {
			/**
			 * Level 1
			 */
			title: string
			desc: string
			src: string
			/**
			 * Al-Amthilah
			 */
			book: string
			explanation: string
		}
		'sarf-bina': {
			/**
			 * Level 2
			 */
			title: string
			desc: string
			src: string
			/**
			 * Sharh Bina al-Afʿāl
			 */
			book: string
			explanation: string
		}
		'sarf-shadha': {
			/**
			 * Level 3
			 */
			title: string
			desc: string
			src: string
			/**
			 * Shadha al-ʿArf
			 */
			book: string
			explanation: string
		}
		'balaghah-durus': {
			/**
			 * Level 1
			 */
			title: string
			desc: string
			src: string
			/**
			 * Durus al-balagha
			 */
			book: string
			explanation: string
		}
		'balaghah-tuhfah': {
			/**
			 * Level 2
			 */
			title: string
			desc: string
			src: string
			/**
			 * Tuhfat al-Ikhwan
			 */
			book: string
			explanation: string
		}
		'balaghah-mukhtasar': {
			/**
			 * Level 3
			 */
			title: string
			desc: string
			src: string
			/**
			 * Mukhtasar al-Maʿāni
			 */
			book: string
			explanation: string
		}
		'balaghah-balaghah': {
			/**
			 * Perusal
			 */
			title: string
			desc: string
			src: string
			/**
			 * Al-Balaghah al-Arabiyyah
			 */
			book: string
			explanation: string
		}
		'balaghah-burdah': {
			/**
			 * Perusal
			 */
			title: string
			desc: string
			src: string
			/**
			 * Al-Burdah: Explanation, Grammar & Balaghah
			 */
			book: string
			explanation: string
		}
		'aqidah-sharh-nazm': {
			/**
			 * Beliefs: Level 1
			 */
			title: string
			/**
			 * A masterful educational poem that's approachable yet vast, with an explanation and commentary
			 */
			desc: string
			/**
			 * /books/aqidah-sharh-nazm.jpg
			 */
			src: string
			/**
			 * Nazm Aqida Ahl al-Sunnah
			 */
			book: string
			explanation: string
		}
		'aqidah-tali': {
			/**
			 * Beliefs: Level 2
			 */
			title: string
			/**
			 * An expert explanation for this major text. This level is sufficient for students not specialzing in beliefs
			 */
			desc: string
			/**
			 * /books/aqidah-tali.jpg
			 */
			src: string
			/**
			 * Taliʿ al-Bushra
			 */
			book: string
			explanation: string
		}
		'aqidah-miftah': {
			/**
			 * Beliefs: Level 3
			 */
			title: string
			/**
			 * A summary of over 50 works in Creed, this book opens the doors of advanced topics to come
			 */
			desc: string
			/**
			 * /books/aqidah-miftah.jpg
			 */
			src: string
			/**
			 * Miftah al-Jannah
			 */
			book: string
			explanation: string
		}
		'aqidah-jawharah': {
			/**
			 * Beliefs: Level 4
			 */
			title: string
			/**
			 * A didactic poem containing most topics of belief, decorated with glimpses of higher truths
			 */
			desc: string
			/**
			 * /books/aqidah-jawharah.jpg
			 */
			src: string
			/**
			 * Jawharat al-Tawhid
			 */
			book: string
			explanation: string
		}
		'aqidah-taftazani': {
			/**
			 * Beliefs: Level 5
			 */
			title: string
			/**
			 * An explanation of a brief yet comprehensive book containing the Sunni beliefs of those who lean to intellectual investigation
			 */
			desc: string
			/**
			 * /books/aqidah-taftazani.jpg
			 */
			src: string
			/**
			 * Sharh al-Nasafiyyah
			 */
			book: string
			explanation: string
		}
		'aqidah-tahrir': {
			/**
			 * Beliefs: Level 6
			 */
			title: string
			/**
			 * A deep dive and joruney through the range of views
			 */
			desc: string
			/**
			 * /books/aqidah-tahrir.jpg
			 */
			src: string
			/**
			 * Tahrir al-Matalib
			 */
			book: string
			explanation: string
		}
		'fiqh-maslak': {
			/**
			 * Fiqh: Level 2
			 */
			title: string
			/**
			 * A complete study of the rulings related to acts of worship: purification, prayer, fasting, zakah & hajj
			 */
			desc: string
			/**
			 * /books/fiqh-maslak.jpg
			 */
			src: string
			/**
			 * Maslak al-Najah
			 */
			book: string
			explanation: string
		}
		'fiqh-lubab': {
			/**
			 * Fiqh: Level 3
			 */
			title: string
			/**
			 * A later work that gathers what came before it to explain the most important Hanafi book
			 */
			desc: string
			/**
			 * /books/fiqh-lubab.jpg
			 */
			src: string
			/**
			 * Al-Lubab
			 */
			book: string
			explanation: string
		}
		'fiqh-hidayah': {
			/**
			 * Fiqh: Level 4
			 */
			title: string
			/**
			 * The source and key for every book in the Madhhab that came after it
			 */
			desc: string
			/**
			 * /books/fiqh-hidayah.jpg
			 */
			src: string
			/**
			 * Al-Hidayah
			 */
			book: string
			explanation: string
		}
		'fiqh-rad': {
			/**
			 * Fiqh: Level 5
			 */
			title: string
			/**
			 * The book relied upon for issuing rulings in the Hanafi madhhab
			 */
			desc: string
			/**
			 * /books/fiqh-rad.jpg
			 */
			src: string
			/**
			 * Radd al-Muhtar
			 */
			book: string
			explanation: string
		}
		'fiqh-manar': {
			/**
			 * Fiqh: Foundations 1
			 */
			title: string
			/**
			 * A brief, comprehensive introduction for the student of foundations and seeker of results
			 */
			desc: string
			/**
			 * /books/fiqh-manar.jpg
			 */
			src: string
			/**
			 * Sharh Mukhtasar al-Manar
			 */
			book: string
			explanation: string
		}
		'fiqh-sharhmanar': {
			/**
			 * Fiqh: Foundations 2
			 */
			title: string
			desc: string
			/**
			 * /books/fiqh-sharhmanar.jpg
			 */
			src: string
			/**
			 * Sharh al-Manar
			 */
			book: string
			explanation: string
		}
		'fiqh-zad': {
			/**
			 * Fiqh: Foundations 3
			 */
			title: string
			desc: string
			/**
			 * /books/fiqh-zad.jpg
			 */
			src: string
			/**
			 * Zad al-Muktafi
			 */
			book: string
			explanation: string
		}
		'fiqh-talwih': {
			/**
			 * Fiqh: Foundations 4
			 */
			title: string
			desc: string
			src: string
			/**
			 * Al-Talwih maʿa al-Tawdih
			 */
			book: string
			explanation: string
		}
		'fiqh-zaydan': {
			/**
			 * Fiqh: Principles 1
			 */
			title: string
			desc: string
			/**
			 * /books/fiqh-zaydan.jpg
			 */
			src: string
			/**
			 * Al-Wajiz Fi al-Qawaid
			 */
			book: string
			explanation: string
		}
		'fiqh-isad': {
			/**
			 * Fiqh: Principles 2
			 */
			title: string
			/**
			 * A poem and explanation explaining everything needed by a Mufti or anyone working with fiqh and the madhhab.
			 */
			desc: string
			/**
			 * /books/fiqh-isad.jpg
			 */
			src: string
			/**
			 * Sharh Uqud Rasm al-Mufti
			 */
			book: string
			explanation: string
		}
		'fiqh-ghamz': {
			/**
			 * Fiqh: Principles 3
			 */
			title: string
			desc: string
			/**
			 * /books/fiqh-ghamz.jpg
			 */
			src: string
			/**
			 * Ghamz al-Basair
			 */
			book: string
			explanation: string
		}
		'fiqh-maram': {
			/**
			 * Fiqh: Evidences 1
			 */
			title: string
			desc: string
			/**
			 * /books/fiqh-maram.jpg
			 */
			src: string
			/**
			 * Sharh Bulugh al-Maram
			 */
			book: string
			explanation: string
		}
		'fiqh-ila': {
			/**
			 * Fiqh: Evidences 2
			 */
			title: string
			desc: string
			/**
			 * /books/fiqh-ila.jpg
			 */
			src: string
			/**
			 * Ila al-Sunan
			 */
			book: string
			explanation: string
		}
		'tasawwuf-bidayah': {
			/**
			 * Spirituality
			 */
			title: string
			/**
			 * The principles of beginnings, which increase Muslims in good activity and correcting their method in that
			 */
			desc: string
			/**
			 * /books/tasawwuf-bidayah.jpg
			 */
			src: string
			/**
			 * Bidayat al-Hidayah
			 */
			book: string
			explanation: string
		}
		'tasawwuf-taj': {
			/**
			 * Spirituality
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-taj.jpg
			 */
			src: string
			/**
			 * Taj al-Arus
			 */
			book: string
			explanation: string
		}
		'tasawwuf-uyub': {
			/**
			 * Spirituality
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-uyub.jpg
			 */
			src: string
			/**
			 * Uyub al-Nafs wa Adwiyatuha
			 */
			book: string
			explanation: string
		}
		'tasawwuf-qasd': {
			/**
			 * Spirituality
			 */
			title: string
			/**
			 * A collection of principles which are the foundation of Tasawwuf and the Path to Allah Almighty
			 */
			desc: string
			/**
			 * /books/tasawwuf-qasd.jpg
			 */
			src: string
			/**
			 * Sharh al-Muntaqa min al-Qawaid
			 */
			book: string
			explanation: string
		}
		'tasawwuf-mabahith': {
			/**
			 * Spirituality
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-mabahith.jpg
			 */
			src: string
			/**
			 * Sharh al-Mabahith al-Asliyyah
			 */
			book: string
			explanation: string
		}
		'tasawwuf-manazil': {
			/**
			 * Spirituality
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-manazil.jpg
			 */
			src: string
			/**
			 * Manazil al-Saʾirin
			 */
			book: string
			explanation: string
		}
		'tasawwuf-himam': {
			/**
			 * Spirituality
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-himam.jpg
			 */
			src: string
			/**
			 * Iqaz al-Himam
			 */
			book: string
			explanation: string
		}
		'tasawwuf-wasaya': {
			/**
			 * Spirituality: Reaching 1
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-wasaya.jpg
			 */
			src: string
			/**
			 * Al-Wasaya
			 */
			book: string
			explanation: string
		}
		'tasawwuf-qawanin': {
			/**
			 * Spirituality: Reaching 2
			 */
			title: string
			/**
			 * One of the most important books of Tasawwuf: innovative in expression and containing major wisdoms in suluk and irfan
			 */
			desc: string
			/**
			 * /books/tasawwuf-qawanin.jpg
			 */
			src: string
			/**
			 * Qawanin Hikam al-Ishraq
			 */
			book: string
			explanation: string
		}
		'tasawwuf-naqsh': {
			/**
			 * Spirituality: Reaching 3
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-naqsh.jpg
			 */
			src: string
			/**
			 * Naqsh al-Fusus
			 */
			book: string
			explanation: string
		}
		'tasawwuf-insankamil': {
			/**
			 * Spirituality: Reaching 4
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-insankamil.jpg
			 */
			src: string
			/**
			 * Al-Insan al-Kamil
			 */
			book: string
			explanation: string
		}
		'tasawwuf-fusus': {
			/**
			 * Spirituality: Reaching 5
			 */
			title: string
			desc: string
			/**
			 * /books/tasawwuf-fusus.jpg
			 */
			src: string
			/**
			 * Fusus al-Hikam
			 */
			book: string
			explanation: string
		}
		'ulumQuran-ulum': {
			/**
			 * Sciences: 1
			 */
			title: string
			/**
			 * A modern book on the Sciences of the Quran by Dr. Nur al-Din Itr, one of the great scholars of the last century
			 */
			desc: string
			/**
			 * Ulum al-Quran
			 */
			book: string
			explanation: string
		}
		'ulumQuran-zubdah': {
			/**
			 * Sciences: Side reading
			 */
			title: string
			/**
			 * A summary of the key text in the field
			 */
			desc: string
			/**
			 * Zubdat al-Itqan
			 */
			book: string
			explanation: string
		}
		'tafsir-durrah': {
			/**
			 * Tafsir: External 1
			 */
			title: string
			/**
			 * Simply phrased, mentioning the incidents of revelation from hadith, with important and precise notes
			 */
			desc: string
			/**
			 * /books/tafsir-durrah.jpg
			 */
			src: string
			/**
			 * Durrah al-Tafasir
			 */
			book: string
			explanation: string
		}
		'tafsir-nasafi': {
			/**
			 * Tafsir: External 2
			 */
			title: string
			/**
			 * A summary of Baydawi's tafsir with clear phrasing and benefits in fiqh and beliefs
			 */
			desc: string
			/**
			 * /books/tafsir-nasafi.jpg
			 */
			src: string
			/**
			 * Tafsir al-Nasafi
			 */
			book: string
			explanation: string
		}
		'tafsir-baydawi': {
			/**
			 * Tafsir: External 3
			 */
			title: string
			desc: string
			/**
			 * /books/tafsir-baydawi.jpg
			 */
			src: string
			/**
			 * Tafsir al-Baydawi
			 */
			book: string
			explanation: string
		}
		'tafsir-qurtubi': {
			/**
			 * Tafsir: External 4
			 */
			title: string
			desc: string
			/**
			 * /books/tafsir-qurtubi.jpg
			 */
			src: string
			/**
			 * Tafsir al-Qurtubi
			 */
			book: string
			explanation: string
		}
		'tafsir-bahr': {
			/**
			 * Tafsir: Ishari 1
			 */
			title: string
			desc: string
			/**
			 * /books/tafsir-bahr.jpg
			 */
			src: string
			/**
			 * Mukhtasar al-Bahr al-Madid
			 */
			book: string
			explanation: string
		}
		'tafsir-waridat': {
			/**
			 * Tafsir: Ishari 2
			 */
			title: string
			desc: string
			/**
			 * /books/tafsir-waridat.jpg
			 */
			src: string
			/**
			 * Al-Waridat al-Ilahiyyah
			 */
			book: string
			explanation: string
		}
		'tafsir-mawaqif': {
			/**
			 * Tafsir: Ishari 3
			 */
			title: string
			desc: string
			/**
			 * /books/tafsir-mawaqif.jpg
			 */
			src: string
			/**
			 * Al-Mawaqif al-Ruhaniyyah
			 */
			book: string
			explanation: string
		}
		'hadith-nawawi': {
			/**
			 * Hadith: Text 1
			 */
			title: string
			/**
			 * Famous Hadith which contain the foundations of the religion and principles of Divine Law
			 */
			desc: string
			/**
			 * /books/hadith-nawawi.jpg
			 */
			src: string
			/**
			 * The 40 Nawawi Hadith
			 */
			book: string
			explanation: string
		}
		'hadith-adab': {
			/**
			 * Hadith: Text 2
			 */
			title: string
			/**
			 * A book of Prophetic, educational ettiquette that inspire the Ummah to folow and be adorned by them
			 */
			desc: string
			/**
			 * /books/hadith-adab.jpg
			 */
			src: string
			/**
			 * Al-Adab al-Mufrad
			 */
			book: string
			explanation: string
		}
		'hadith-riyad': {
			/**
			 * Hadith: Text 3
			 */
			title: string
			/**
			 * A short collection of strong hadith, with rectification for our hearts and actions, making clear the way to the afterlife
			 */
			desc: string
			/**
			 * /books/hadith-riyad.jpg
			 */
			src: string
			/**
			 * Riyad al-Salihin
			 */
			book: string
			explanation: string
		}
		'hadith-bukhari': {
			/**
			 * Hadith: Text 4
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-bukhari.jpg
			 */
			src: string
			/**
			 * Sahih al-Bukhari
			 */
			book: string
			explanation: string
		}
		'hadith-muslim': {
			/**
			 * Hadith: Text 5
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-muslim.jpg
			 */
			src: string
			/**
			 * Sahih Muslim
			 */
			book: string
			explanation: string
		}
		'hadith-tirmidhi': {
			/**
			 * Hadith: Text 6
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-tirmidhi.jpg
			 */
			src: string
			/**
			 * Sunan al-Tirmidhi
			 */
			book: string
			explanation: string
		}
		'hadith-abudawud': {
			/**
			 * Hadith: Text 7
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-abudawud.jpg
			 */
			src: string
			/**
			 * Sunan Abu Dawud
			 */
			book: string
			explanation: string
		}
		'hadith-ibnmajah': {
			/**
			 * Hadith: Text 8
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-ibnmajah.jpg
			 */
			src: string
			/**
			 * Sunan ibn Majah
			 */
			book: string
			explanation: string
		}
		'hadith-nasai': {
			/**
			 * Hadith: Text 9
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-nasai.jpg
			 */
			src: string
			/**
			 * Sunan al-Nasai
			 */
			book: string
			explanation: string
		}
		'hadith-musnad': {
			/**
			 * Hadith: Text 10
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-musnad.jpg
			 */
			src: string
			/**
			 * Musnad Ahmad
			 */
			book: string
			explanation: string
		}
		'hadith-darimi': {
			/**
			 * Hadith: Text 11
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-darimi.jpg
			 */
			src: string
			/**
			 * Sunan al-Darimi
			 */
			book: string
			explanation: string
		}
		'hadith-muwatta': {
			/**
			 * Hadith: Text 12
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-muwatta.jpg
			 */
			src: string
			/**
			 * Al-Muwatta
			 */
			book: string
			explanation: string
		}
		'hadith-bayquni': {
			/**
			 * Hadith: Terminology 1
			 */
			title: string
			/**
			 * Introducing the most famous Hadith sciences and the needed explanations and terminology
			 */
			desc: string
			/**
			 * /books/hadith-bayquni.jpg
			 */
			src: string
			/**
			 * Sharh al-Bayquniyyah
			 */
			book: string
			explanation: string
		}
		'hadith-nuzhah': {
			/**
			 * Hadith: Terminology 2
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-nuzhah.jpg
			 */
			src: string
			/**
			 * Nuzhah al-Nazar
			 */
			book: string
			explanation: string
		}
		'hadith-salah': {
			/**
			 * Hadith: Terminology 3
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-salah.jpg
			 */
			src: string
			/**
			 * Muqaddimah Ibn al-Salah
			 */
			book: string
			explanation: string
		}
		'hadith-tadrib': {
			/**
			 * Hadith: Terminology 4
			 */
			title: string
			desc: string
			/**
			 * /books/hadith-tadrib.jpg
			 */
			src: string
			/**
			 * Tadrib al-Rawi
			 */
			book: string
			explanation: string
		}
		'sirah-halabi': {
			/**
			 * Seerah 1
			 */
			title: string
			/**
			 * A refined edition of a trusted reference in Prophetic Biography, containing fluid writing, accurate reports and deep explanations
			 */
			desc: string
			/**
			 * /books/sirah-halabi.jpg
			 */
			src: string
			/**
			 * Tahdhib al-Seerah al-Halabiyyah
			 */
			book: string
			explanation: string
		}
		'sirah-wasail': {
			/**
			 * Shamail 1
			 */
			title: string
			/**
			 * A brief book that gathers the traits of the Prophet, blessings and peace upon him, with explanations
			 */
			desc: string
			/**
			 * /books/sirah-wasail.jpg
			 */
			src: string
			/**
			 * Wasail al-Wusul
			 */
			book: string
			explanation: string
		}
		'other-isa': {
			/**
			 * Logic
			 */
			title: string
			/**
			 * An explanation of the foundational text in the study of Logic
			 */
			desc: string
			/**
			 * /books/other-isa.jpg
			 */
			src: string
			/**
			 * Mughni al-Tullab
			 */
			book: string
			explanation: string
		}
		'other-diwankurdi': {
			/**
			 * Inshad & Singing
			 */
			title: string
			desc: string
			/**
			 * /books/other-diwankurdi.jpg
			 */
			src: string
			/**
			 * Diwan al-Shaykh al-Kurdi
			 */
			book: string
			explanation: string
		}
	}
	contact: {
		/**
		 * Contact us from below to inquire about any course and register
		 */
		courses: string
		/**
		 * Get in touch with us through 
		 */
		contact_us: string
		/**
		 * Email
		 */
		email: string
		/**
		 *  or 
		 */
		or: string
		/**
		 * Telegram
		 */
		telegram: string
	}
	payment: {
		/**
		 * Payment successful!
		 */
		successful_alert: string
		/**
		 * Something went wrong
		 */
		error: string
		/**
		 * $140 (all proceeds are re-invested into the Center's projects)
		 */
		price_140: string
	}
	/**
	 * The Inner & Outer Sciences
	 */
	slogan: string
}

export type TranslationFunctions = {
	/**
	 * Knowledge & Insight
	 */
	title: () => LocalizedString
	/**
	 * The Center For
	 */
	center: () => LocalizedString
	/**
	 * ltr
	 */
	direction: () => LocalizedString
	coursePage: {
		/**
		 * About this course
		 */
		about: () => LocalizedString
	}
	hero: {
		/**
		 * Islamic Knowledge, Prophetic Spirituality
		 */
		header1: () => LocalizedString
		/**
		 * Complete Islamic Knowledge Taught by Scholars
		 */
		subheader1: () => LocalizedString
	}
	about: {
		/**
		 * About
		 */
		title: () => LocalizedString
	}
	welcome: {
		/**
		 * Begin or continue your studies with our complete curriculum covering all the religious sciences
		 */
		complete_curriculum: () => LocalizedString
		/**
		 * Our mission is to link students to true scholars, who connect them to the Noble Prophet (ﷺ).
		 */
		mission: () => LocalizedString
		/**
		 * Access your lessons and recordings wherever you are—learning always goes on.
		 */
		online: () => LocalizedString
		/**
		 * Benefit now from the library of articles and videos that will continue tog row inshaAllah
		 */
		articles: () => LocalizedString
	}
	shaykh: {
		/**
		 * Supervisor
		 */
		heading: () => LocalizedString
		/**
		 * Honorable Shaykh Abd al-Rahman al-Sha'ar
		 */
		subheading: () => LocalizedString
		/**
		 * Shaykh Abd al-Rahman al-Sha’ar began seeking knowledge at a young age, being nurtured by scholars and those who love knowledge. He dedicated his life to the service of Islam and studied complete curriculums in all its areas, including: Quran, Hadith, Fiqh, Aqida, Tasawwuf, Arabic and its sciences, and more. He received all this divine knowledge at the hands of lordly scholars, attaining full license to teach all the inner and the outer religious sciences from many of the top scholars of the past century. Today, he dedicates himself to producing both books  and inheritors of the highest standard.
		 */
		short_bio: () => LocalizedString
		/**
		 * Learn more about the Shaykh
		 */
		button: () => LocalizedString
		/**
		 * Short Biography
		 */
		long_bio_title: () => LocalizedString
		/**
		 * His Studies
		 */
		long_bio_studies_title: () => LocalizedString
		/**
		 * Shaykh ʿAbd al-Raḥmān began seeking knowledge and memorizing the noble Qur’an in Masjid al-Ashmar and Masjid Zayd b. Thābit. He then entered Maʿhad al-Fatḥ al-Islāmī and graduated with honors. He would attend the classes of a number of great scholars in Syria, such as Shaykh ʿAbd al-Razzāq al-Ḥalabī’s morning lessons in the Umayyad Mosque, Shaykh Khalīl al-Ṣabbāgh’s lessons in Masjid Ward al-Kabīr, and the erudite Shaykh Usāma al-Rifāʿī’s classes in the Masjid of ʿAbd al-Karīm al-Rifāʿī. He memorized parts of the Qur’an under the tutelage of Shaykh Shukrī al-Luḥafī and Shaykh Muḥammad al-Sayyid Ismāʿīl Abū Munīr.
		 */
		long_bio_studies_1: () => LocalizedString
		/**
		 * Shaykh ʿAbd al-Raḥmān attended the lessons of Shaykh Muḥammad Jumuʿa for ten years and studied many books with him in various sciences in Maʿhad al-Fatḥ as well as outside of it. Among the books Shaykh ʿAbd al-Raḥmān read in Ḥanafī fiqh are: Marāqī al-Falāḥ, al-Ikhtiyār li-Taʿlīl al-Mukhtār, two-thirds of Ḥāshiyat Ibn ʿĀbidīn, some of Sharḥ al-Jaṣṣāṣ ʿalá Mukhtaṣar al-Ṭahāwī, Badā’iʿ al-Ṣanā’iʿ, Sharḥ al-Taṣrīḥ ʿalá al-Tawḍīḥ, and Tafsīr al-Nasafī. Shaykh ʿAbd al-Raḥmān also read al-Aṣl: Mabsūṭ al-Imām Muḥammad and al-Lubāb: Sharḥ al-Kitāb by himself and reviewed more difficult passages with Shaykh Muḥammad Jumuʿa. 
		 */
		long_bio_studies_2: () => LocalizedString
		/**
		 * He attended the lessons of Shaykh Muḥammad Shuqayr in Masjid al-Ḥasan and studied many works with him, such as al-Risāla al-Qushayriyya, Sunan Abī Dāwūd, al-Jāmiʿ by al-Tirmidhī, Sharḥ Ibn ʿAqīl, al-Nahw al-Wāḍiḥ, Iḥyā’ ʿUlūm al-Dīn, al-Adhkār, and Sharḥ al-Nawawī ʿalá Ṣaḥīḥ Muslim. Shaykh ʿAbd al-Raḥmān attended the lessons of the erudite scholar Shaykh Muḥammad Abū al-Hudá al-Yaʿqūbī, studying with him Sharḥ Umm al-Barāhīn by al-Sanūsī in the Umayyad Mosque and Qawā’id al-Taṣawwuf in the Masjid of Muḥyī al-Dīn b. al-ʿArabī. He attended the lessons of Shaykh Muḥammad Asʿad al-Ṣāgharjī, reading with him Sharḥ al-Mabāḥith al-Aṣliyya by ibn ʿAjība and al-Fatḥ al-Rabbāni by Shaykh ʿAbd al-Qādir al-Jīlānī. He also attended the lessons of Shaykh Ḥassān al-Hindī, read with him at Maʿhad al-Fatḥ and after graduating, and benefitted greatly from him. He read Ṣaḥīḥ al-Bukhārī with Shaykh Naʿīm ʿAraqsūsī. Shaykh ʿAbd al-Raḥmān attended the gatherings of ḥadīth held by Shaykh ʿUmar Nashūqātī in Masjid al-Ḥājibiyya, studied other sciences, and read several books with him, including al-Adab al-Mufrad by al-Bukhārī, al-Muwaṭṭa’ by Imam Mālik, al-Āthār by Imam Muḥammad, and the Shamā’il of Imam al-Tirmidhī.
		 */
		long_bio_studies_3: () => LocalizedString
		/**
		 * His Spiritual Path and Taṣawwuf
		 */
		long_bio_spirituality_title: () => LocalizedString
		/**
		 * Shaykh ʿAbd al-Raḥmān grew up under the nurturing wing of Shaykh ʿAbd al-Raḥmān al-Shāghūrī as his father took him to the public and private lessons of the shaykh. Shaykh ʿAbd al-Raḥmān adored Shaykh al-Shāghūrī from a young age; the latter would consistently go out of his way for Shaykh ʿAbd al-Raḥmān until God took back Shaykh al-Shāghūrī’s soul in 2004, when Shaykh ʿAbd al-Raḥmān was only eighteen years old. Consequently, Shaykh ʿAbd al-Raḥmān continued the path of taṣawwuf under the guidance of Shaykh Muṣṭafá al-Turkmānī, consistently attending and recording his lessons for seven years until the shaykh’s passing. Shaykh ʿAbd al-Raḥmān then completed the path under the guidance of Shaykh Shukrī al-Luḥafī; upon his instruction, Shaykh ʿAbd al-Raḥmān entered spiritual seclusion (khalwa). He was also the head singer at Shaykh Shukrī’s public and private gatherings, accompanying him for several years.
		 */
		long_bio_spirituality_1: () => LocalizedString
		/**
		 * Afterwards, Shaykh Muḥammad Amīn al-Fārūqī requested that Shaykh ʿAbd al-Raḥmān enter spiritual seclusion under him; thereafter, he specially authorized Shaykh ʿAbd al-Raḥmān in the path to give spiritual guidance, enter others into spiritual seclusions, and prescribe the Singular Name [i.e., a spiritual practice involving repetition of the name ‘Allāh’].
		 */
		long_bio_spirituality_2: () => LocalizedString
		/**
		 * Shaykh ʿAbd al-Raḥmān then entered another spiritual seclusion under Shaykh ʿAbd al-Bāqī Miftāḥ al-Jazā’irī, who also authorized him in the path, and then with Shaykh Ḥasan al-Anṣārī al-Jazā’irī, who would authorize him as well. Among the greats he benefitted most from in the arena of experiential Sufism was Shaykh Kamāl al-Ḥusaynī al-Shamīsātī, one of the students of Shaykh Muḥammad al-Hāshimī.
		 */
		long_bio_spirituality_3: () => LocalizedString
	}
	goals: {
		/**
		 * Spreading the inner and outer sciences as Imam al-Ghazali accomplished – Allah be pleased with him.
		 */
		'1': () => LocalizedString
		/**
		 * Perfecting the reading of the Noble Quran in recitation and tajwid, with a linked chain of ascription and ijaza certification in the Ten Readings – all upon the way the noble Companions received the Quran from the Prophet – peace and blessings upon him –along with reviving the role of the Quran in Muslims’ souls.
		 */
		'2': () => LocalizedString
		/**
		 * Reviving the service of the Prophetic Sunnah and the noble Science of Hadith in both narration and understanding. Furthermore, resetting the compass of the Ummah towards following the guidance of the Prophet – Allah send peace and blessings upon him – and also his biography (Sirah), so that the Ummah can gain peace and be saved.
		 */
		'3': () => LocalizedString
		/**
		 * Explaining the obligatory knowledge every Muslim man and woman must know—for a slave of Allah to worship his Lord upon based guidance and be free of sins based on his ignorance of that.
		 */
		'4': () => LocalizedString
		/**
		 * Teaching the correct beliefs of the righteous predecessors (Salaf). This is done through the Sunni method as demonstrated in the beliefs of the Ashʿari, Maturidi, and Athar approaches, along with the understanding of the lordly scholars and knowers of the Ummah.
		 */
		'5': () => LocalizedString
		/**
		 * Explaining the detailed rulings of the Divine law of Allah (Shariʿa) in accordance with the Four Imams – Allah be pleased upon them. Thus, a Muslim can apply his religion correctly in accordance with the pure Sharia, and his actions can be built upon Fiqh and sound knowledge, allowing one to worship Allah Almighty based upon guidance and leave the prison of ignorance and the forbidden..
		 */
		'6': () => LocalizedString
		/**
		 * Spreading the correct spirituality (tasawwuf) which is the soul of the religion, what’s been named ihsan. This includes both spiritual seeking and enlightened understanding. This is for a Muslim to leave all sins and follow the way of the Master of All Creation in worshipping His lord with witnessing and awareness that he himself is being witnessed, which leads to complete inheritance and following.
		 */
		'7': () => LocalizedString
		/**
		 * Teaching the Arabic language, the language of the Quan and the Beloved Prophet – peace and blessings upon him. This is to correctly understand the words of Allah Almighty and the purified prophetic Sunnah, and the words of the scholars. Indeed, it has been said: “Whoever does not perfect the Arabic language, is not trusted in his knowledge.”
		 */
		'8': () => LocalizedString
		/**
		 * Perfecting the tool-sciences such as rhetoric (maʿani), expression (bayan), linguistic devices (badiʿ), etymology (sarf), grammar (nahw), poetic meters, and logic. A student of knowledge needs all of them in order to completely absorb knowledge and then present it in the best way possible.
		 */
		'9': () => LocalizedString
		/**
		 * Training in dawah, public speaking and poetry skills, all of which are essential in benefitting others, through an approach where one can express things in a clear, convincing, and moving way.
		 */
		'10': () => LocalizedString
		/**
		 * Our goal
		 */
		goal: () => LocalizedString
		/**
		 * Reviving the religious sciences by
		 */
		title: () => LocalizedString
	}
	wisdoms: {
		/**
		 * Supervisor's Wisdoms
		 */
		title: () => LocalizedString
		list: {
			/**
			 * The truly joyous don't strive for ijazats and certificates
			 */
			ijaza_1: () => LocalizedString
		}
	}
	articles: {
		/**
		 * Articles
		 */
		title: () => LocalizedString
		knowledge_good_intentions: {
			/**
			 * Good Intentions – Advice for Students of Knowledge 1
			 */
			title: () => LocalizedString
			/**
			 * ترجمة الوصايا لطالب العلم الوصية الأولى\nAdvice for Students of Knowledge
		Advice 1: Good Intentions\nThe Prophet, peace and blessings be upon him, said, “Actions are only by intention, and for every man is only what he intended.”\nThe first obligation upon a student of knowledge is to make a good intention for his knowledge and teaching. A good, sincere intention is the greatest of elixirs — the good and benefit of an action is multiplied in accordance with the plentitude of intentions.
		Some the intentions that a student of knowledge should have are the following:\n- Preservation of the Book of Allah and the Sunnah of His Messenger, peace and blessings be upon him\n- Obedience to the command of the Beloved, peace and blessings be upon him\n- Listening to and transmitting the speech of the Messenger of Allah, peace and blessings be upon him\n- Lifting sins from oneself and fellow Muslims by learning and teaching the personal and communal obligations\n- Exposure to the winds of Divine Mercy in order to attain His pleasure\n- Remembrance and reminder\n- Preserving one’s time \n- Spreading the sacred teachings of Islam \n- I`tikāf (religious seclusion) if the gathering is in the mosque \n- Renewal of faith\n- Mutual assistance to piety,  mindfulness of God, commanding the good, and forbidding the evil\n- Increasing the collective body of the people of good \n- Seeking the mercy of Allah to descend by remembering the righteous\n- Purification of the inward and struggling against the lower self\n- Acting according to one’s knowledge Oh Allah, make our knowledge, actions, teaching, and the rest of our actions sincere for Your Noble Countenance, by the rank of Your Greatest Beloved, peace and blessings be upon him and his beloveds.\n A servant of this noble knowledge,\nAbd al-Rahman al-Sha`ār\n02/21/19
			 */
			content: () => LocalizedString
		}
	}
	tags: {
		/**
		 * Obligatory Knowledge
		 */
		fard: () => LocalizedString
		/**
		 * The Prophet said - Allah bless him and send him peace: "Seeking knowledge is mandatory upon every Muslim." The Scholars have explained that this obligatory knowledge on every Muslim man and women are five: Beliefs, Tajwid to correct what is recited in Salah, Fiqh of Worship & Interactions, and Purification of the soul.
		 */
		fard_explanation: () => LocalizedString
		/**
		 * Beliefs
		 */
		aqidah: () => LocalizedString
		/**
		 * Truly, Beliefs is the most noble religious science. It is the bedrock of all obligations, and the foundation of all commands—because it is linked to the Divine Being. This is why it's mandatory for every Muslim to learn what will correct his beliefs, as Allah Almighty said: "And I have not created jinn or human beings except to worship Me." [51:56] Ibn Jurayj explained: "That means: 'To know Me.'"
		 */
		aqidah_explanation: () => LocalizedString
		/**
		 * Seerah & Shamail
		 */
		sirah: () => LocalizedString
		/**
		 * Works of Prophetic Biography & Description give out rays of light, the light of Islamic principles and lofty ettiqutte. It is what allows one to udnerstand the book of Allah Almighty and its goals. Surely the Prophet (peace and blessings upon him) is the practical example of all that is in the Quran, as Lady Aisha (Allah be pleased upon her) said: 'His ettiquette was the Quran.'
		 */
		sirah_explanation: () => LocalizedString
		/**
		 * Assorted Programs
		 */
		program: () => LocalizedString
		program_explanation: () => LocalizedString
		/**
		 * Arabic for Non-natives
		 */
		natiq: () => LocalizedString
		/**
		 * After learning the knowledge obligatory upon every Muslim, learning Arabic for non-Arabs is a life-changing improvement, allowing them to understand the Quran, Sunnah, and Scholars directly without any barrier.
		 */
		natiq_explanation: () => LocalizedString
		/**
		 * Various Courses
		 */
		misc: () => LocalizedString
		/**
		 * Various Courses
		 */
		misc_explanation: () => LocalizedString
		/**
		 * Quran Recitation & Tajwid
		 */
		tajwid: () => LocalizedString
		/**
		 * Theoretical
		 */
		tajwid_nazari: () => LocalizedString
		/**
		 * Practical
		 */
		tajwid_amali: () => LocalizedString
		/**
		 * Truly the science of Tajwid is part of the knowledge obligatory for every Muslim to learn – to the extent by which Salah is valid. The goal of Tajwid is giving the Quran and each letter in it its right, and to recite as the Prophet (peace and blessings upon him) recited.
		 */
		tajwid_explanation: () => LocalizedString
		/**
		 * Arabic & Its Sciences
		 */
		arabi: () => LocalizedString
		/**
		 * Nahw
		 */
		arabi_nahw: () => LocalizedString
		/**
		 * Sarf
		 */
		arabi_sarf: () => LocalizedString
		/**
		 * Balaghah
		 */
		arabi_balaghah: () => LocalizedString
		/**
		 * "Indeed Allah Almighty honored the Arabic language out of all others, by making it the vessel for His Noble Book and the Sunnah of His Prophet - Allah send blessings and peace upon him - the Almighty said: "We have sent it down as an Arabic Quran so that you may understand" [Yusuf: 2]. Thus, it is the tongue of the clear Divine law and it's study is widespread and an inseparable part of the religion."
		 */
		arabi_explanation: () => LocalizedString
		/**
		 * Fiqh & Its Foundations
		 */
		fiqh: () => LocalizedString
		/**
		 * Rulings
		 */
		fiqh_rulings: () => LocalizedString
		/**
		 * Foundations
		 */
		fiqh_foundations: () => LocalizedString
		/**
		 * Principles
		 */
		fiqh_principles: () => LocalizedString
		/**
		 * Evidences
		 */
		fiqh_evidences: () => LocalizedString
		/**
		 * Truly Fiqh is one of the noblest and greatest religious sciences - after learning what corrects his belief. Indeed, Fiqh corrects a person's worship and interactions, allowing him to worship Allah upon guidance, getting to know Him in the worldy life upto the levels of the rigtheous, and in the afterlife upto the ranks of the best. Allah make us of them by His generosity and favor!
		 */
		fiqh_explanation: () => LocalizedString
		/**
		 * Spirituality
		 */
		tasawwuf: () => LocalizedString
		/**
		 * Self-purification & Suluk
		 */
		tasawwuf_suluk: () => LocalizedString
		/**
		 * Higher Realities
		 */
		tasawwuf_irfan: () => LocalizedString
		/**
		 * There is no doubt that Tasawwuf (Spirituality) is the most beneficial knowledge, because it is the way to clear the soul of its flaws and filth, and adorning it with higher truths and realities, and purifying it with precise and wonderful details. Thus it is the beneficial knowledge the fruit of which is fear of Allah Almighty. Real Spirituality is what makes clear the behavioural, nurturing and development method - and after that the spiritual. It is made up of three stages: cleansing, adorning and manifesting.
		 */
		tasawwuf_explanation: () => LocalizedString
		/**
		 * The Quran & Its Sciences
		 */
		tafsir: () => LocalizedString
		/**
		 * Ishari Tafsir
		 */
		tafsir_ishari: () => LocalizedString
		/**
		 * External Tafsir
		 */
		tafsir_zahir: () => LocalizedString
		/**
		 * Quran Sciences
		 */
		ulum_quran: () => LocalizedString
		/**
		 * "Truly the Quran is the book of guidance for mankind, it guides them to the upright, and leads them to what is good for their worldly- and afterlife. Among the most important things a Muslim must be concerned about and focus on: reflecting on the Quran and understanding its meanings. That is the way to success in this life and the next, and this is not possible except by returning to what the Scholars of Tafsir have written about the Words of Allah Almighty."
		 */
		tafsir_explanation: () => LocalizedString
		/**
		 * Hadith & Its Sciences
		 */
		hadith: () => LocalizedString
		/**
		 * Hadith Texts
		 */
		hadith_texts: () => LocalizedString
		/**
		 * Hadith Sciences
		 */
		hadith_sciences: () => LocalizedString
		/**
		 * Surely the Prophetic Sunnah is the source of Islam and reviver of Iman in the hearts. Whoever reads these noble hadith is in the company of the Messenger of Allah (peace and blessings upon him), receiving knowledge and insight from him. And truly the scholars of Islam have precisely preserved all these narrations with the utmost excellence and clarity.
		 */
		hadith_explanation: () => LocalizedString
		/**
		 * Assorted Classes
		 */
		other: () => LocalizedString
		other_explanation: () => LocalizedString
		/**
		 * Dawah & Outreach
		 */
		'public': () => LocalizedString
	}
	courses: {
		/**
		 * Courses
		 */
		title: () => LocalizedString
		'tajwid-qaida': {
			/**
			 * /books/tajwid-qaida.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tajwid: Level 1
			 */
			title: () => LocalizedString
			/**
			 * A practical first text to reciting the Noble Quran correctly with tajwid
			 */
			desc: () => LocalizedString
			/**
			 * Al-Qaida al-Nuraniyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tajwid-hidayatrahman': {
			/**
			 * Tajwid: Level 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tajwid-hidayatrahman.jpg
			 */
			src: () => LocalizedString
			/**
			 * Hidayat al-Rahman
			 */
			book: () => LocalizedString
		}
		'tajwid-thani': {
			/**
			 * Tajwid: Level 3
			 */
			title: () => LocalizedString
			/**
			 * Written by the expert scholar Yahya al-Ghawthani
			 */
			desc: () => LocalizedString
			/**
			 * /books/tajwid-thani.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Mustawa al-Thani
			 */
			book: () => LocalizedString
		}
		'tajwid-jazari': {
			/**
			 * Tajwid: Level 4
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tajwid-jazari.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh al-Jazariyyah
			 */
			book: () => LocalizedString
		}
		'tajwid-amma': {
			/**
			 * Level 1: Open-book Recitation
			 */
			title: () => LocalizedString
			/**
			 * Apply the rules of tajwid to these regularly read surah!
			 */
			desc: () => LocalizedString
			/**
			 * /books/mushaf.jpg
			 */
			src: () => LocalizedString
			/**
			 * Quran Juz 30: ʿAmma
			 */
			book: () => LocalizedString
		}
		'tajwid-reading': {
			/**
			 * Level 2: Open-book Recitation
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/mushaf.jpg
			 */
			src: () => LocalizedString
			/**
			 * The Entire Quran
			 */
			book: () => LocalizedString
		}
		'tajwid-reciting': {
			/**
			 * Level 3: Reciting from Memory
			 */
			title: () => LocalizedString
			/**
			 * In all 10 recitations, depending on the student's aims
			 */
			desc: () => LocalizedString
			/**
			 * /books/mushaf.jpg
			 */
			src: () => LocalizedString
			/**
			 * The Entire Quran for Ijaza
			 */
			book: () => LocalizedString
		}
		'fiqh-nur': {
			/**
			 * Fiqh of Worship: 1
			 */
			title: () => LocalizedString
			/**
			 * Essential rules for a Muslim's worship and all things related to that
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-nur.jpg
			 */
			src: () => LocalizedString
			/**
			 * Nur al-Idah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-quduri': {
			/**
			 * Fiqh of Interactions: 1
			 */
			title: () => LocalizedString
			/**
			 * Essential rules for a Muslim's dealings  with Allah's creation and his relations
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-quduri.jpg
			 */
			src: () => LocalizedString
			/**
			 * Mukhtasar al-Quduri
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'aqidah-ahl-sunnah': {
			/**
			 * Beliefs: Essentials
			 */
			title: () => LocalizedString
			/**
			 * The obligatory beliefs for every Muslim in a brief and simple text
			 */
			desc: () => LocalizedString
			/**
			 * /books/aqidah-ahl-sunnah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Aqida Ahl al-Sunnah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-rawdah': {
			/**
			 * Spirituality: Introduction
			 */
			title: () => LocalizedString
			/**
			 * The essential introduction to Ihsan in every part of life to get closer to Allah Almighty
			 */
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-rawdah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Radwat al-Ushaq
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-tuhfah': {
			/**
			 * Spirituality: Essentials
			 */
			title: () => LocalizedString
			/**
			 * Rectifying worship, regular actions, and repairing the bad traits of the heart
			 */
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-tuhfah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tuhfat al-Salikin
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-fuyud': {
			/**
			 * Spirituality: Essentials
			 */
			title: () => LocalizedString
			/**
			 * A collection of commanding hadith, with explanations to help bring them to life
			 */
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-fuyud.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Fuyud al-Ahmadiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'program-youth': {
			/**
			 * A complete program spanning several books
			 */
			title: () => LocalizedString
			/**
			 * This is placeholder of some text, we need to write later
			 */
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Youth Program
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'program-women': {
			/**
			 * A complete program spanning several books
			 */
			title: () => LocalizedString
			/**
			 * This is placeholder of some text, we need to write later
			 */
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Women's Program
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'natiq-um1': {
			/**
			 * Preparatory Level
			 */
			title: () => LocalizedString
			/**
			 * Starting from how to pronounce letters, all the way to communicating in everyday situations
			 */
			desc: () => LocalizedString
			/**
			 * /books/natiq-um1.jpg
			 */
			src: () => LocalizedString
			/**
			 * Silsilah al-Lisan: 1
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'natiq-um2': {
			/**
			 * Beginner Level
			 */
			title: () => LocalizedString
			/**
			 * Students begin learning a foundation in Arabic grammar and sentence construction.
			 */
			desc: () => LocalizedString
			/**
			 * /books/natiq-um2.jpg
			 */
			src: () => LocalizedString
			/**
			 * Silsilah al-Lisan: 2
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'natiq-um3': {
			/**
			 * Intermediate Level
			 */
			title: () => LocalizedString
			/**
			 * Learners start composing short essays, cover more topics for vocabulary, and expand their grammar.
			 */
			desc: () => LocalizedString
			/**
			 * /books/natiq-um3.jpg
			 */
			src: () => LocalizedString
			/**
			 * Silsilah al-Lisan: 3
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'natiq-um4': {
			/**
			 * Advanced Level
			 */
			title: () => LocalizedString
			/**
			 * Training to write long texts, dialogues and being able to handle any Arabic book or reference
			 */
			desc: () => LocalizedString
			/**
			 * /books/natiq-um4.jpg
			 */
			src: () => LocalizedString
			/**
			 * Silsilah al-Lisan: 4
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'nahw-mabadi': {
			/**
			 * Level 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Mabadiʾ Durus al-Arabiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'nahw-tawdih': {
			/**
			 * Level 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Al-Tawdih: Sharh al-Ajurumiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'nahw-tashil': {
			/**
			 * Level 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Al-Tashil: Sharh al-Ajurumiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'nahw-durus': {
			/**
			 * Level 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Durus Nahwiyya
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'nahw-qatr': {
			/**
			 * Level 4
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Sharh Qatr al-Nada
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'nahw-alfiyyah': {
			/**
			 * Level 5
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Al-Alfiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'nahw-ibnaqil': {
			/**
			 * Level 6
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Sharh ibn Aqīl
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'sarf-amthilah': {
			/**
			 * Level 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Al-Amthilah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'sarf-bina': {
			/**
			 * Level 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Sharh Bina al-Afʿāl
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'sarf-shadha': {
			/**
			 * Level 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Shadha al-ʿArf
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'balaghah-durus': {
			/**
			 * Level 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Durus al-balagha
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'balaghah-tuhfah': {
			/**
			 * Level 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Tuhfat al-Ikhwan
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'balaghah-mukhtasar': {
			/**
			 * Level 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Mukhtasar al-Maʿāni
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'balaghah-balaghah': {
			/**
			 * Perusal
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Al-Balaghah al-Arabiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'balaghah-burdah': {
			/**
			 * Perusal
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Al-Burdah: Explanation, Grammar & Balaghah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'aqidah-sharh-nazm': {
			/**
			 * Beliefs: Level 1
			 */
			title: () => LocalizedString
			/**
			 * A masterful educational poem that's approachable yet vast, with an explanation and commentary
			 */
			desc: () => LocalizedString
			/**
			 * /books/aqidah-sharh-nazm.jpg
			 */
			src: () => LocalizedString
			/**
			 * Nazm Aqida Ahl al-Sunnah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'aqidah-tali': {
			/**
			 * Beliefs: Level 2
			 */
			title: () => LocalizedString
			/**
			 * An expert explanation for this major text. This level is sufficient for students not specialzing in beliefs
			 */
			desc: () => LocalizedString
			/**
			 * /books/aqidah-tali.jpg
			 */
			src: () => LocalizedString
			/**
			 * Taliʿ al-Bushra
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'aqidah-miftah': {
			/**
			 * Beliefs: Level 3
			 */
			title: () => LocalizedString
			/**
			 * A summary of over 50 works in Creed, this book opens the doors of advanced topics to come
			 */
			desc: () => LocalizedString
			/**
			 * /books/aqidah-miftah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Miftah al-Jannah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'aqidah-jawharah': {
			/**
			 * Beliefs: Level 4
			 */
			title: () => LocalizedString
			/**
			 * A didactic poem containing most topics of belief, decorated with glimpses of higher truths
			 */
			desc: () => LocalizedString
			/**
			 * /books/aqidah-jawharah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Jawharat al-Tawhid
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'aqidah-taftazani': {
			/**
			 * Beliefs: Level 5
			 */
			title: () => LocalizedString
			/**
			 * An explanation of a brief yet comprehensive book containing the Sunni beliefs of those who lean to intellectual investigation
			 */
			desc: () => LocalizedString
			/**
			 * /books/aqidah-taftazani.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh al-Nasafiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'aqidah-tahrir': {
			/**
			 * Beliefs: Level 6
			 */
			title: () => LocalizedString
			/**
			 * A deep dive and joruney through the range of views
			 */
			desc: () => LocalizedString
			/**
			 * /books/aqidah-tahrir.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tahrir al-Matalib
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-maslak': {
			/**
			 * Fiqh: Level 2
			 */
			title: () => LocalizedString
			/**
			 * A complete study of the rulings related to acts of worship: purification, prayer, fasting, zakah & hajj
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-maslak.jpg
			 */
			src: () => LocalizedString
			/**
			 * Maslak al-Najah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-lubab': {
			/**
			 * Fiqh: Level 3
			 */
			title: () => LocalizedString
			/**
			 * A later work that gathers what came before it to explain the most important Hanafi book
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-lubab.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Lubab
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-hidayah': {
			/**
			 * Fiqh: Level 4
			 */
			title: () => LocalizedString
			/**
			 * The source and key for every book in the Madhhab that came after it
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-hidayah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Hidayah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-rad': {
			/**
			 * Fiqh: Level 5
			 */
			title: () => LocalizedString
			/**
			 * The book relied upon for issuing rulings in the Hanafi madhhab
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-rad.jpg
			 */
			src: () => LocalizedString
			/**
			 * Radd al-Muhtar
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-manar': {
			/**
			 * Fiqh: Foundations 1
			 */
			title: () => LocalizedString
			/**
			 * A brief, comprehensive introduction for the student of foundations and seeker of results
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-manar.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh Mukhtasar al-Manar
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-sharhmanar': {
			/**
			 * Fiqh: Foundations 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/fiqh-sharhmanar.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh al-Manar
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-zad': {
			/**
			 * Fiqh: Foundations 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/fiqh-zad.jpg
			 */
			src: () => LocalizedString
			/**
			 * Zad al-Muktafi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-talwih': {
			/**
			 * Fiqh: Foundations 4
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			src: () => LocalizedString
			/**
			 * Al-Talwih maʿa al-Tawdih
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-zaydan': {
			/**
			 * Fiqh: Principles 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/fiqh-zaydan.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Wajiz Fi al-Qawaid
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-isad': {
			/**
			 * Fiqh: Principles 2
			 */
			title: () => LocalizedString
			/**
			 * A poem and explanation explaining everything needed by a Mufti or anyone working with fiqh and the madhhab.
			 */
			desc: () => LocalizedString
			/**
			 * /books/fiqh-isad.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh Uqud Rasm al-Mufti
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-ghamz': {
			/**
			 * Fiqh: Principles 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/fiqh-ghamz.jpg
			 */
			src: () => LocalizedString
			/**
			 * Ghamz al-Basair
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-maram': {
			/**
			 * Fiqh: Evidences 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/fiqh-maram.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh Bulugh al-Maram
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'fiqh-ila': {
			/**
			 * Fiqh: Evidences 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/fiqh-ila.jpg
			 */
			src: () => LocalizedString
			/**
			 * Ila al-Sunan
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-bidayah': {
			/**
			 * Spirituality
			 */
			title: () => LocalizedString
			/**
			 * The principles of beginnings, which increase Muslims in good activity and correcting their method in that
			 */
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-bidayah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Bidayat al-Hidayah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-taj': {
			/**
			 * Spirituality
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-taj.jpg
			 */
			src: () => LocalizedString
			/**
			 * Taj al-Arus
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-uyub': {
			/**
			 * Spirituality
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-uyub.jpg
			 */
			src: () => LocalizedString
			/**
			 * Uyub al-Nafs wa Adwiyatuha
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-qasd': {
			/**
			 * Spirituality
			 */
			title: () => LocalizedString
			/**
			 * A collection of principles which are the foundation of Tasawwuf and the Path to Allah Almighty
			 */
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-qasd.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh al-Muntaqa min al-Qawaid
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-mabahith': {
			/**
			 * Spirituality
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-mabahith.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh al-Mabahith al-Asliyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-manazil': {
			/**
			 * Spirituality
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-manazil.jpg
			 */
			src: () => LocalizedString
			/**
			 * Manazil al-Saʾirin
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-himam': {
			/**
			 * Spirituality
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-himam.jpg
			 */
			src: () => LocalizedString
			/**
			 * Iqaz al-Himam
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-wasaya': {
			/**
			 * Spirituality: Reaching 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-wasaya.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Wasaya
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-qawanin': {
			/**
			 * Spirituality: Reaching 2
			 */
			title: () => LocalizedString
			/**
			 * One of the most important books of Tasawwuf: innovative in expression and containing major wisdoms in suluk and irfan
			 */
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-qawanin.jpg
			 */
			src: () => LocalizedString
			/**
			 * Qawanin Hikam al-Ishraq
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-naqsh': {
			/**
			 * Spirituality: Reaching 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-naqsh.jpg
			 */
			src: () => LocalizedString
			/**
			 * Naqsh al-Fusus
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-insankamil': {
			/**
			 * Spirituality: Reaching 4
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-insankamil.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Insan al-Kamil
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tasawwuf-fusus': {
			/**
			 * Spirituality: Reaching 5
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tasawwuf-fusus.jpg
			 */
			src: () => LocalizedString
			/**
			 * Fusus al-Hikam
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'ulumQuran-ulum': {
			/**
			 * Sciences: 1
			 */
			title: () => LocalizedString
			/**
			 * A modern book on the Sciences of the Quran by Dr. Nur al-Din Itr, one of the great scholars of the last century
			 */
			desc: () => LocalizedString
			/**
			 * Ulum al-Quran
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'ulumQuran-zubdah': {
			/**
			 * Sciences: Side reading
			 */
			title: () => LocalizedString
			/**
			 * A summary of the key text in the field
			 */
			desc: () => LocalizedString
			/**
			 * Zubdat al-Itqan
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tafsir-durrah': {
			/**
			 * Tafsir: External 1
			 */
			title: () => LocalizedString
			/**
			 * Simply phrased, mentioning the incidents of revelation from hadith, with important and precise notes
			 */
			desc: () => LocalizedString
			/**
			 * /books/tafsir-durrah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Durrah al-Tafasir
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tafsir-nasafi': {
			/**
			 * Tafsir: External 2
			 */
			title: () => LocalizedString
			/**
			 * A summary of Baydawi's tafsir with clear phrasing and benefits in fiqh and beliefs
			 */
			desc: () => LocalizedString
			/**
			 * /books/tafsir-nasafi.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tafsir al-Nasafi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tafsir-baydawi': {
			/**
			 * Tafsir: External 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tafsir-baydawi.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tafsir al-Baydawi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tafsir-qurtubi': {
			/**
			 * Tafsir: External 4
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tafsir-qurtubi.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tafsir al-Qurtubi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tafsir-bahr': {
			/**
			 * Tafsir: Ishari 1
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tafsir-bahr.jpg
			 */
			src: () => LocalizedString
			/**
			 * Mukhtasar al-Bahr al-Madid
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tafsir-waridat': {
			/**
			 * Tafsir: Ishari 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tafsir-waridat.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Waridat al-Ilahiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'tafsir-mawaqif': {
			/**
			 * Tafsir: Ishari 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/tafsir-mawaqif.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Mawaqif al-Ruhaniyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-nawawi': {
			/**
			 * Hadith: Text 1
			 */
			title: () => LocalizedString
			/**
			 * Famous Hadith which contain the foundations of the religion and principles of Divine Law
			 */
			desc: () => LocalizedString
			/**
			 * /books/hadith-nawawi.jpg
			 */
			src: () => LocalizedString
			/**
			 * The 40 Nawawi Hadith
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-adab': {
			/**
			 * Hadith: Text 2
			 */
			title: () => LocalizedString
			/**
			 * A book of Prophetic, educational ettiquette that inspire the Ummah to folow and be adorned by them
			 */
			desc: () => LocalizedString
			/**
			 * /books/hadith-adab.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Adab al-Mufrad
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-riyad': {
			/**
			 * Hadith: Text 3
			 */
			title: () => LocalizedString
			/**
			 * A short collection of strong hadith, with rectification for our hearts and actions, making clear the way to the afterlife
			 */
			desc: () => LocalizedString
			/**
			 * /books/hadith-riyad.jpg
			 */
			src: () => LocalizedString
			/**
			 * Riyad al-Salihin
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-bukhari': {
			/**
			 * Hadith: Text 4
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-bukhari.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sahih al-Bukhari
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-muslim': {
			/**
			 * Hadith: Text 5
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-muslim.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sahih Muslim
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-tirmidhi': {
			/**
			 * Hadith: Text 6
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-tirmidhi.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sunan al-Tirmidhi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-abudawud': {
			/**
			 * Hadith: Text 7
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-abudawud.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sunan Abu Dawud
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-ibnmajah': {
			/**
			 * Hadith: Text 8
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-ibnmajah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sunan ibn Majah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-nasai': {
			/**
			 * Hadith: Text 9
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-nasai.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sunan al-Nasai
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-musnad': {
			/**
			 * Hadith: Text 10
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-musnad.jpg
			 */
			src: () => LocalizedString
			/**
			 * Musnad Ahmad
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-darimi': {
			/**
			 * Hadith: Text 11
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-darimi.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sunan al-Darimi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-muwatta': {
			/**
			 * Hadith: Text 12
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-muwatta.jpg
			 */
			src: () => LocalizedString
			/**
			 * Al-Muwatta
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-bayquni': {
			/**
			 * Hadith: Terminology 1
			 */
			title: () => LocalizedString
			/**
			 * Introducing the most famous Hadith sciences and the needed explanations and terminology
			 */
			desc: () => LocalizedString
			/**
			 * /books/hadith-bayquni.jpg
			 */
			src: () => LocalizedString
			/**
			 * Sharh al-Bayquniyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-nuzhah': {
			/**
			 * Hadith: Terminology 2
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-nuzhah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Nuzhah al-Nazar
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-salah': {
			/**
			 * Hadith: Terminology 3
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-salah.jpg
			 */
			src: () => LocalizedString
			/**
			 * Muqaddimah Ibn al-Salah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'hadith-tadrib': {
			/**
			 * Hadith: Terminology 4
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/hadith-tadrib.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tadrib al-Rawi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'sirah-halabi': {
			/**
			 * Seerah 1
			 */
			title: () => LocalizedString
			/**
			 * A refined edition of a trusted reference in Prophetic Biography, containing fluid writing, accurate reports and deep explanations
			 */
			desc: () => LocalizedString
			/**
			 * /books/sirah-halabi.jpg
			 */
			src: () => LocalizedString
			/**
			 * Tahdhib al-Seerah al-Halabiyyah
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'sirah-wasail': {
			/**
			 * Shamail 1
			 */
			title: () => LocalizedString
			/**
			 * A brief book that gathers the traits of the Prophet, blessings and peace upon him, with explanations
			 */
			desc: () => LocalizedString
			/**
			 * /books/sirah-wasail.jpg
			 */
			src: () => LocalizedString
			/**
			 * Wasail al-Wusul
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'other-isa': {
			/**
			 * Logic
			 */
			title: () => LocalizedString
			/**
			 * An explanation of the foundational text in the study of Logic
			 */
			desc: () => LocalizedString
			/**
			 * /books/other-isa.jpg
			 */
			src: () => LocalizedString
			/**
			 * Mughni al-Tullab
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
		'other-diwankurdi': {
			/**
			 * Inshad & Singing
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
			/**
			 * /books/other-diwankurdi.jpg
			 */
			src: () => LocalizedString
			/**
			 * Diwan al-Shaykh al-Kurdi
			 */
			book: () => LocalizedString
			explanation: () => LocalizedString
		}
	}
	contact: {
		/**
		 * Contact us from below to inquire about any course and register
		 */
		courses: () => LocalizedString
		/**
		 * Get in touch with us through 
		 */
		contact_us: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 *  or 
		 */
		or: () => LocalizedString
		/**
		 * Telegram
		 */
		telegram: () => LocalizedString
	}
	payment: {
		/**
		 * Payment successful!
		 */
		successful_alert: () => LocalizedString
		/**
		 * Something went wrong
		 */
		error: () => LocalizedString
		/**
		 * $140 (all proceeds are re-invested into the Center's projects)
		 */
		price_140: () => LocalizedString
	}
	/**
	 * The Inner & Outer Sciences
	 */
	slogan: () => LocalizedString
}

export type Formatters = {}
