<script context="module">
	import { onMount, afterUpdate } from 'svelte'
</script>

<script lang="ts">
	import Header from '$lib/Header.svelte'
	import { documentDirectionUpdated } from '$lib/stores'
	// delaying display till the document direction is set,
	// so there is no ugly flip of content for eng users.

	import { setLocale, locale } from '$i18n/i18n-svelte'
	import type { LayoutData } from './$types'
	export let data: LayoutData

	setLocale(data.locale)
</script>

<Header />

{#if $documentDirectionUpdated}
	<main>
		<slot />
	</main>
{:else}
	<div class="loadingio-spinner-parent">
		<div class="spinner">
			<div />
			<div />
			<div />
			<div />
			<div />
			<div />
			<div />
			<div />
			<div />
		</div>
	</div>
{/if}

<style lang="scss" global>
	@import '../styles/global.scss';
	main {
		padding: 0 12rem;
	}
	@media only screen and (max-width: 1000px) {
		main {
			padding: 0 5rem;
		}
	}
	@media only screen and (max-width: 600px) {
		main {
			padding: 0;
		}
	}
	.loadingio-spinner-parent {
		width: 100vw;
		margin: 100px auto 0 auto;
	}
	.loadingio-spinner-parent {
		width: 141px;
		height: 141px;
		display: inline-block;
		overflow: hidden;
		background: rgba(255, 255, 255, 0);
	}
	.spinner {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.spinner div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
	@keyframes spinner {
		0% {
			opacity: 1;
		}
		100% {
			opacity: 0;
		}
	}
	.spinner div {
		left: 52.875px;
		top: 0px;
		position: absolute;
		animation: spinner linear 0.5434782608695652s infinite;
		background: #466075;
		width: 35.25px;
		height: 19.74px;
		border-radius: 17.625px / 9.87px;
		transform-origin: 17.625px 70.5px;
	}
	.spinner div:nth-child(1) {
		transform: rotate(0deg);
		animation-delay: -0.48309178743961345s;
		background: #466075;
	}
	.spinner div:nth-child(2) {
		transform: rotate(40deg);
		animation-delay: -0.42270531400966177s;
		background: #466075;
	}
	.spinner div:nth-child(3) {
		transform: rotate(80deg);
		animation-delay: -0.3623188405797101s;
		background: #466075;
	}
	.spinner div:nth-child(4) {
		transform: rotate(120deg);
		animation-delay: -0.3019323671497584s;
		background: #466075;
	}
	.spinner div:nth-child(5) {
		transform: rotate(160deg);
		animation-delay: -0.24154589371980673s;
		background: #466075;
	}
	.spinner div:nth-child(6) {
		transform: rotate(200deg);
		animation-delay: -0.18115942028985504s;
		background: #466075;
	}
	.spinner div:nth-child(7) {
		transform: rotate(240deg);
		animation-delay: -0.12077294685990336s;
		background: #466075;
	}
	.spinner div:nth-child(8) {
		transform: rotate(280deg);
		animation-delay: -0.06038647342995168s;
		background: #466075;
	}
	.spinner div:nth-child(9) {
		transform: rotate(320deg);
		animation-delay: 0s;
		background: #466075;
	}
	
</style>
